### ISSUE TITLE
持仓金额每日收益能不能做成实时的

### ISSUE THREAD

**Issue by ZhZhenT** [LeekHub/leek-fund#112]
研发大大，持仓金额每日收益能不能做成实时的，每次需要点击左侧金额图标才能刷新收益

**Comment by giscafer** [comment]
盈亏是实时的啊。净值没更新的时候不会修改持仓总金额。

盈亏实时显示方式：个性化设置——>显示盈亏

> 每次需要点击左侧金额图标才能刷新收益 这个没懂。是bug吗？盈亏一直是实时的呀。

**Comment by giscafer** [comment]
v1.8.7 持仓金额设置页面，新增手动刷新按钮。不实时因为此页面是编辑页面，刷新数据可能会和编辑的行为冲突。
