### ISSUE TITLE
允许拖拽排序，排序按钮添加选择框

### ISSUE THREAD

**Issue by quanzaiyu** [LeekHub/leek-fund#126]
## Feature Request

1. 股票、基金列表希望能进行拖拽排序
2. 点击排序按钮后，出现一个Picker选择框，Options可以是 [股票代码、涨幅升序、涨幅降序] 等。现在每次去点击排序按钮并不清楚当前是什么排序是什么

**Comment by giscafer** [comment]
界面视图无法实现，这个和代码文件一样，你打开代码工程，代码文件能拖拽排序吗？一个道理和实现方式。

技术上实现也可行，需要进入webview去渲染排序，保存顺序数组，在刷新基金视图。
这样操作就和app那种不一样了，步骤多了一个，效率也不高了。所以之前没考虑该功能
