### ISSUE TITLE
股价提醒优化

### ISSUE THREAD

**Issue by Peter-90** [LeekHub/leek-fund#136]
## Bug Report
当设置股价下跌提醒时，在早上未开盘期间，股价为0.00，这个时候会提示下跌到了0.00

## Current Behavior?
<img width="478" alt="iShot2020-12-21 09 10 45" src="https://user-images.githubusercontent.com/22003137/102729807-3be08c00-436d-11eb-8a1e-a48de97669b7.png">

## Expected Behavior?
感觉这个可以优化一下，不用提示

**Comment by wujunchuan** [comment]
可以加个判断:

当前价格 = 0 时, 不进行股价提示
