### ISSUE TITLE
设置持仓金额页面，希望增加按收益率升序排序功能

### ISSUE THREAD

**Issue by 89333367** [LeekHub/leek-fund#143]
![image](https://user-images.githubusercontent.com/20157752/103324591-295c0600-4a83-11eb-92b3-a75569f64989.png)

如果能排序一下就好看了

**Comment by giscafer** [comment]
这里其实和列表视图那里排序是保持一致的，因为列表那里没有按收益率功能排序（有了持仓金额排序）。所以这类没有。加也是可以，懂前端欢迎PR参与共建
