### ISSUE TITLE
希望增加当日盈亏到底部状态栏或者侧边栏

### ISSUE THREAD

**Issue by yylzcom** [LeekHub/leek-fund#148]
请描述下这个功能的作用：

  1、这个功能的使用场景是什么？
  2、这个功能解决你的什么问题？
-->
目前每次都需要点开“韭菜盒子”，然后再点“设置基金持仓金额”才能看到当日总的盈亏

希望能把当日总盈亏：
显示在vscode底部状态栏或者侧边栏基金详情的下方， 这样更方便查看

谢谢作者这么好的插件！

**Comment by giscafer** [comment]
侧边栏目前无法实现。单独给盈亏开个view也不合理。转态栏可以考虑。懂的欢迎PR
