### ISSUE TITLE
状态栏监控在白色主题下字体颜色问题

### ISSUE THREAD

**Issue by suenchunyu** [LeekHub/leek-fund#149]
## Bug Report

状态栏监控在白色主题下字体颜色也为白色，导致看不见实际被监控的基金内容

## Current Behavior?

![image](https://user-images.githubusercontent.com/20114873/103840853-59338b00-50cd-11eb-9d2a-c2e71b91364c.png)

## Expected Behavior?

状态栏监控字体颜色可配置，亦或者可根据当前主题为Dark或Light自动切换字体颜色

**Comment by giscafer** [comment]
字体颜色可以自定义哦。请细看功能。
