### ISSUE TITLE
希望在基金持仓金额设置页面，增加按持仓金额排序功能

### ISSUE THREAD

**Issue by 89333367** [LeekHub/leek-fund#153]
希望在基金持仓金额设置页面，增加按持仓金额排序功能
由于我的基金比较多，手动修改持仓金额和持仓成本的时候，上下找容易找错行，如果可以按持仓金额排序，我就可以对照手机的列表修改金额了，手机是安装持仓金额倒序的。

![image](https://user-images.githubusercontent.com/20157752/104253679-0c2a2d00-54b0-11eb-8fa5-46d9db603e69.png)

**Comment by giscafer** [comment]
外部列表支持持仓金额排序。排序完，该页面刷新一下就是了。由于功能重叠，就不加了。懂开发可以PR一下会合并。
