### ISSUE TITLE
1.9.2版本状态栏基金盈亏不显示，始终为0

### ISSUE THREAD

**Issue by Peter-90** [LeekHub/leek-fund#154]

**Comment by Peter-90** [comment]
@giscafer 大佬 有时间看一下这个问题 有这个功能不能用挺难受的

**Comment by yylzcom** [comment]
我的正常... 超级喜欢这个功能
持仓金额设置了吗

**Comment by Peter-90** [comment]
@yylzcom 设置了 在那个持仓页面是显示当日盈亏的，只是状态栏不显示

**Comment by giscafer** [comment]
正常显示啊。群里反馈问问群友看看。或者自己 Ctrl+ Shit + P 输入 ： toggle developer 看看有没有什么错误

**Comment by Peter-90** [comment]
<img width="1212" alt="iShot2021-01-13 20 01 40" src="https://user-images.githubusercontent.com/22003137/104449838-2eb86500-55da-11eb-8573-bc089238a3c6.png">
@giscafer 看起来没有报错 但是就是没有显示

**Comment by giscafer** [comment]
最新代码应该解决了，没发版

**Comment by Peter-90** [comment]
@giscafer 大佬啥时候发版 从出来就在期待中

**Comment by giscafer** [comment]
先关闭。新版本后续会更新
