### ISSUE TITLE
基金持仓金额页面无法保存数据

### ISSUE THREAD

**Issue by Leo4ML** [LeekHub/leek-fund#156]
版本：1.9.2
其实在1.9.2之前的任一版本里，我都无法成功设置基金持仓成本和金额。点击保存后，再点刷新或者关掉页面再次打开持仓金额页面，显示都是0。这也导致了无法查看基金收益。这个功能急切需要修复。

**Comment by giscafer** [comment]
@Leo4ML 昨天使用过正常的。问问群友看看是不是只有自己有问题？

**Comment by giscafer** [comment]
@Leo4ML 1.9.3再试看看

**Comment by Leo4ML** [comment]
> @Leo4ML 1.9.3再试看看

1.9.3可以成功保存，问题解决！
