### ISSUE TITLE
能否加入监控工行或者招行纸白银、纸黄金的价格动态的功能

### ISSUE THREAD

**Issue by waitxxxx** [LeekHub/leek-fund#158]
请描述下这个功能的作用：

  1、这个功能的使用场景是什么？
    A: 监控工行或者招行纸白银、纸黄金的价格动态。
  2、这个功能解决你的什么问题？
   A: 监控工行或者招行纸白银、纸黄金的价格动态。及时调整进出

**Comment by giscafer** [comment]
欢迎PR

**Comment by daxiajunjun** [comment]
顺便支持下期货盯盘呀
