### ISSUE TITLE
隐藏黄鸡

### ISSUE THREAD

**Issue by xgdgsc** [LeekHub/leek-fund#160]
请描述下这个功能的作用：

  1、这个功能的使用场景是什么？
不需要基金，只看下涨跌
  2、这个功能解决你的什么问题？
黄鸡占地方

**Comment by wujunchuan** [comment]
我也觉得, 没啥用

https://github.com/giscafer/leek-fund/blob/f3dd6c5d3cde979d42327101b4b8e05ab4b596ac/src/statusbar/statusBar.ts#L121-L127

**Comment by giscafer** [comment]
目标没有可替代的图标。有替代方案可以提，隐藏不是个好办法，因为无法代表“基金”的意思。
有需要可以扩展开关去控制隐藏。但不会直接隐藏次功能，别人可能需要。欢迎PR

**Comment by giscafer** [comment]
手动改配置 `"leek-fund.hideFundBarItem": false`
