### ISSUE TITLE
能够借用github，进行配置数据同步？

### ISSUE THREAD

**Issue by WQMDC** [LeekHub/leek-fund#161]
插件中配置好了持仓的基金，并且配置好了持仓金额等等，但是换了一台电脑，就要重新配置一遍。能否支持持仓数据间的同步？

其实就是通过把插件的config上传到自己的github上，然后再另外一台电脑上下载下来，并运用。

**Comment by wujunchuan** [comment]
插件的配置信息都写在 `~/Library/Application Support/Code/User/settings.json` 中

vscode 现在不是官方已经支持 `Settings Sync` 了吗, 用这个在不同设备上同步配置就行

**Comment by songjiang951130** [comment]
我就需要这个功能
