### ISSUE TITLE
希望可以添加盯盘的功能

### ISSUE THREAD

**Issue by ZY1014** [LeekHub/leek-fund#166]
## Feature Request

请描述下这个功能的作用：
  1、设置固定的股票盯盘
  2、可以实时关注自选股票异动？
  3、类似目前韭菜盒子-快讯功能

**Comment by giscafer** [comment]
这太专业了吧。不写代码了吗？

**Comment by giscafer** [comment]
欢迎PR，暂时关闭

**Comment by giscafer** [comment]
v4.2.3 支持个股异动

<img width="1427" height="1156" alt="Image" src="https://github.com/user-attachments/assets/9787baf7-15a6-4463-b7c7-0c8f86bedd9a" />
