### ISSUE TITLE
希望可以添加港股基金

### ISSUE THREAD

**Issue by SuperNG6** [LeekHub/leek-fund#167]
现在只能从settings.json里手动添加，直接搜索的话会搜索不到

**Comment by giscafer** [comment]
你看这里有没有 https://github.com/LeekHub/leek-fund/blob/master/src/data/fundSuggestData.ts

**Comment by OrbitPortal** [comment]
> 你看这里有没有 https://github.com/LeekHub/leek-fund/blob/master/src/data/fundSuggestData.ts

96xxxx的好像都没有，我提供几个：
968040|HLJZRMBFDC|惠理价值人民币非对冲|中港互认|
968041|HLJZRMBDC|惠理价值人民币对冲|中港互认|
968061|MGTPYKJRMBDC|摩根太平洋科技人民币对冲|中港互认|
968062|MGTPYKJRMB|摩根太平洋科技人民币|中港互认|
968072|MGYZZZRMBDC|摩根亚洲增长人民币对冲|中港互认|
968073|MGYZZZRMB|摩根亚洲增长人民币|中港互认|

（虽然港基净值更新跟QDII一样慢就是了……）
