### ISSUE TITLE
无法设置基金持仓

### ISSUE THREAD

**Issue by bruceCzK** [LeekHub/leek-fund#172]
删除所有配置重新安装也无法设置持仓金额。

VSCode 版本信息
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

![image](https://user-images.githubusercontent.com/8399711/105141287-e3e7a180-5b33-11eb-86b9-701c6b488273.png)

**Comment by yuanmaitian** [comment]
无法添加基金持仓，无论如何设置
