### ISSUE TITLE
部分股票数据有出入

### ISSUE THREAD

**Issue by tnuoccalanosrep** [LeekHub/leek-fund#173]
007807 建信MSCI中国A股指数增强C 数据跟支付宝的基金涨跌幅是有出入的，支付宝为正，这里为负，没看过代码，目测数据源是有出入，可以检查下，之前也有人提过issue，说能否切源，我觉得工作量挺大，不同平台 api 以及 response data 都不一样

**Comment by giscafer** [comment]
支付宝的基金估值不准。接口是天天基金的。股票的目前新浪的。后续会考虑支持别的数据源。关闭此issue。移步：#165
