### ISSUE TITLE
希望增加一个基金分组的功能

### ISSUE THREAD

**Issue by fgf01** [LeekHub/leek-fund#179]
分组功能：

1、所有基金都属于默认分组。
2、然后可以分组查看自己定义的基金组。
3、如果基金数量多的话。个性化更高一些，也便于管理

**Comment by 90hacker** [comment]
等你加入进来，完善功能

**Comment by badasslittlepig** [comment]
<img width="140" alt="image" src="https://user-images.githubusercontent.com/13128412/195048883-c404e837-dab5-4952-998a-c1616b8c43af.png">
这个有了
