### ISSUE TITLE
控制台【输出】能否配置是否输出log，目前log有点影响日常开发

### ISSUE THREAD

**Issue by zicong-zhang** [LeekHub/leek-fund#181]

**Comment by giscafer** [comment]
有的，雪球新闻那里有个开关。

**Comment by zicong-zhang** [comment]
> 有的，雪球新闻那里有个开关。

![image](https://user-images.githubusercontent.com/32116218/106562175-e3ec9600-6564-11eb-9c19-556cedf70cf2.png)

雪球新闻的开关我试了，但是还是无法关闭【fetching fund data……】这行log

**Comment by zicong-zhang** [comment]
> 有的，雪球新闻那里有个开关。

![image](https://user-images.githubusercontent.com/32116218/106562175-e3ec9600-6564-11eb-9c19-556cedf70cf2.png)

雪球新闻的开关我试了，但是还是无法关闭【fetching fund data……】这行log
