### ISSUE TITLE
fetching stock data… fetching fund data…… 这两个输出可以配置关掉吗

### ISSUE THREAD

**Issue by zicong-zhang** [LeekHub/leek-fund#182]
## Feature Request

抱歉另开了一个 issue
1、期望可以关闭这两个 log 的输出
## Other reference [Optional]

https://github.com/LeekHub/leek-fund/issues/181

**Comment by giscafer** [comment]
为什么开发会看到这个面板呢？开发vscode 插件？

**Comment by zicong-zhang** [comment]
> 为什么开发会看到这个面板呢？开发vscode 插件？

是的，公司内部研发了一些自用的vscode插件，也在【输出】面板里打log

**Comment by giscafer** [comment]
可配置去掉，欢迎PR。加个 debug配置即可

**Comment by giscafer** [comment]
有需求欢迎PR，先关闭
