### ISSUE TITLE
[BUG]亏损数据正负不统一，导致总盈亏计算错误

### ISSUE THREAD

**Issue by cnDelbert** [LeekHub/leek-fund#184]
## Bug Report

![image](https://user-images.githubusercontent.com/3842387/107003474-cff49e80-67c7-11eb-831c-8898211ac1d4.png)
亏损的数据有的是正数，有的是负数，导致最终计算结果不对。

譬如今天亏损 1412.75，但是实际显示亏损770.63：

![image](https://user-images.githubusercontent.com/3842387/107003607-06321e00-67c8-11eb-901d-c2e05df58cee.png)

> 1412.75 + 321.06 + 321.06 = 770.63

盈亏和实际数据显示的正负不一致。

## Current Behavior?

盈亏和实际数据显示的正负不一致。

## Expected Behavior?

盈为正，亏为负。
不要有的盈利 -500，有的亏损 +500

**Comment by giscafer** [comment]
这个封闭基金比较特殊，可能存在没测试到位的bug

**Comment by giscafer** [comment]
#330
