### ISSUE TITLE
leek-fund.hideStatusBarStock 设置无效

### ISSUE THREAD

**Issue by Kcium** [LeekHub/leek-fund#186]
## Current Behavior?

默认是 false
通过对此设置为 true，无效， 
"leek-fund.hideStatusBarStock”: true

## Expected Behavior?

这里如果设置了 true，应该隐藏的

##  Your Environment [Optional]

macOS Catalina 10.15.7

Visual Studio Code  Version: 1.53.1

**Comment by giscafer** [comment]
这个只是隐藏黄鸡。详情见：#160

隐藏状态栏的话是vscode编辑器功能，右键状态栏即可操作

**Comment by Kcium** [comment]
> 这个只是隐藏黄鸡。详情见：#160
> 
> 隐藏状态栏的话是vscode编辑器功能，右键状态栏即可操作


这个我倒是找到了一个比较hack的方法来实现了
