### ISSUE TITLE
第二天未开盘时，显示的盈亏数据错误

### ISSUE THREAD

**Issue by Peter-90** [LeekHub/leek-fund#188]
## Bug Report
![image](https://user-images.githubusercontent.com/22003137/109088306-27908500-774a-11eb-98a0-6bb26829f28a.png)
我持有的基金，在当天实时估算盈亏的数据是正确的，但是第二天未开盘前显示的就不是前一天估算的盈亏数值了，并且数值与实际盈亏也没有关联性，不知道这个数值是怎么计算出来的（持仓金额在前一天收盘后第二天显示是没有问题的）

## Expected Behavior?
应该显示的是前一天估算的盈亏或者是基金收盘后实际的盈亏

##  Your Environment [Optional]
macOS Catalina 10.15.7 vscode 1.53.2 插件版本 1.9.5

**Comment by giscafer** [comment]
这个是直接拿天天基金接口数据展示的，接口数据是什么就展示什么。 接口不会更新成实际的涨幅。而是前一天的大致估值。
