### ISSUE TITLE
你好，股票涨跌提醒要怎么设置？

### ISSUE THREAD

**Issue by kingcard1131** [LeekHub/leek-fund#189]
"leek-fund.stocksRemind": {
        

        "hk01810"
        "sz002077"
        "sz000333"
        "sz002959"
        "sh600480"
}
这样可以吗？

**Comment by giscafer** [comment]
不要改配置，请使用韭菜中心

**Comment by kingcard1131** [comment]
> 不要改配置，请使用韭菜中心，股票详情右侧有增加价格涨跌提醒

好的，非常感谢！感谢你的付出。

**Comment by kingcard1131** [comment]
> 不要改配置，请使用韭菜中心，股票详情右侧有增加价格涨跌提醒

还有一个问题，复制请求头的cookis，怎么复制，请求头在哪里？
