### ISSUE TITLE
插件（养🐥）交流群

### ISSUE THREAD

**Issue by giscafer** [LeekHub/leek-fund#19]
群的用途

- 收集反馈的建议
- 技（🐥）术学习交流

二维码：

关注公众号，回复："加群"，获取群主微信二维码，加好友后邀请加入**插件（养 🐥）微信交流群**：

<img width="300" alt="微信公众号" src="https://raw.sevencdn.com/LeekHub/leek-fund/master/screenshot/wechat-qr1.jpg">

---

**不方便微信交流或者怕打扰的可以加入 电报群[Telegram](https://t.me/joinchat/VKxykRyeRNcibg7I-ykZMg) **

**Comment by iawes** [comment]
除了升降序，可以按照配置顺序固定股票排序吗？或者置顶某几只股票。
因为要关注已经买的股票。

**Comment by giscafer** [comment]
> 除了升降序，可以按照配置顺序固定股票排序吗？或者置顶某几只股票。
> 因为要关注已经买的股票。

将来可以支持

**Comment by gitdy** [comment]
除了升降序，可以按照配置顺序固定股票排序吗？或者置顶某几只股票。
因为要关注已经买的股票。 也需要这个

**Comment by giscafer** [comment]
> 除了升降序，可以按照配置顺序固定股票排序吗？或者置顶某几只股票。
> 因为要关注已经买的股票。 也需要这个
现在排序有三种：1、升序；2、降序；3、不排序（默认配置代码的顺序）

不排序就是你说的吧？你只需要把你要重点关注的放到配置的数组的前面就可以了。

在不支持自定义排序之前，就手动改配置文件的数组元素顺序吧。

**Comment by iawes** [comment]
> 
> 
> > 除了升降序，可以按照配置顺序固定股票排序吗？或者置顶某几只股票。
> > 因为要关注已经买的股票。 也需要这个
> 
> **现在排序有三种**：1、升序；2、降序；3、不排序（默认配置代码的顺序）
> 
> 不排序就是你说的吧？你只需要把你要重点关注的放到配置的数组的前面就可以了。
> 
> 在不支持自定义排序之前，就手动改配置文件的数组元素顺序吧。

嗯嗯，已经解决了，这个问题是好久之前发的。

**Comment by hugewilliam** [comment]
大佬，微信群二维码过期了

**Comment by giscafer** [comment]
> 大佬，微信群二维码过期了

已更新

**Comment by liqianfei** [comment]
感谢大佬，大佬辛苦了

**Comment by liuxu379** [comment]
IDEA给我上！

**Comment by giscafer** [comment]
> IDEA给我上！

Idea 就没有那么快乐的开发了。

**Comment by RSchuxuezhe** [comment]
请问可以批量导出基金的历史净值吗？每条基金的历史净值可以延申到1年吗？

**Comment by giscafer** [comment]
> 请问可以批量导出基金的历史净值吗？每条基金的历史净值可以延申到1年吗？

点击查看更多，跳转到天天基金，想看多少看多少

**Comment by GUEThe** [comment]
![bug](https://user-images.githubusercontent.com/19553651/94636492-af8f7180-0307-11eb-91fe-8266af913b7a.gif)
网络不好的时候右下角一直有闪屏提示

**Comment by giscafer** [comment]
@GUEThe 新浪接口不支持代理，这个可能没法解决，接口问题。你开启了VPN 吗？

**Comment by yguozhen** [comment]
请问基金有没有前一日净值排序的功能啊？因为当前排序是估算，会有一定误差（低的有0.1% 多的有2%）

**Comment by giscafer** [comment]
> 请问基金有没有前一日净值排序的功能啊？因为当前排序是估算，会有一定误差（低的有0.1% 多的有2%）

没有哦

**Comment by liuxu379** [comment]
> > IDEA给我上！
> 
> Idea 就没有那么快乐的开发了。

;you

> > IDEA给我上！
> 
> Idea 就没有那么快乐的开发了。

请问有提上日程吗？有的话预计什么什么时间段能发布？

**Comment by giscafer** [comment]
> > > IDEA给我上！
> > 
> > 
> > Idea 就没有那么快乐的开发了。
> 
> ;you
> 
> > > IDEA给我上！
> > 
> > 
> > Idea 就没有那么快乐的开发了。
> 
> 请问有提上日程吗？有的话预计什么什么时间段能发布？

不开发idea。个人是前端开发，Idea用得少

**Comment by erices1** [comment]
![image](https://user-images.githubusercontent.com/29652465/98322481-77740080-2022-11eb-813c-c95987f2fde8.png)
收益率应该留两位小数，不然挤坏布局了

**Comment by erices1** [comment]
![image](https://user-images.githubusercontent.com/29652465/98322570-b013da00-2022-11eb-9ff3-71a450af6cd4.png)
收益率小数留太多了，搞得页面都乱了

**Comment by giscafer** [comment]
> ![image](https://user-images.githubusercontent.com/29652465/98322570-b013da00-2022-11eb-9ff3-71a450af6cd4.png)
> 收益率小数留太多了，搞得页面都乱了

确认是否是最新的 1.7.0 版本。按理最新版本没有这个问题了。

**Comment by konnga** [comment]
这样调用api，不怕被告吗？

**Comment by Milet-Mistic** [comment]
VSCode小白想问一下，韭菜盒子不小心用活动栏移除以后，不知道怎么能开启活动栏显示，状态栏OK

**Comment by giscafer** [comment]
> VSCode小白想问一下，韭菜盒子不小心用活动栏移除以后，不知道怎么能开启活动栏显示，状态栏OK

右键菜单勾选

**Comment by Milet-Mistic** [comment]
> > VSCode小白想问一下，韭菜盒子不小心用活动栏移除以后，不知道怎么能开启活动栏显示，状态栏OK
> 
> 右键菜单勾选

感谢大大的回答，我右键菜单里面没有这个勾选项，我怀疑是不是我的globalConfig文件里面改勒设置了什么东西，我其他的插件类似TODO tree都是正常的。我再尝试尝试下，活动栏没有以后连添加新股都不行😂

**Comment by xpzero** [comment]
更新版本后没有之前的基金数据了，也不能添加基金，但是setting文件中有之前的数据

**Comment by m-yingyi** [comment]
更新之后，一片空白，显示：‘无数据，请检查网络或添加基金’，也不能添加基金······

**Comment by giscafer** [comment]
> 更新之后，一片空白，显示：‘无数据，请检查网络或添加基金’，也不能添加基金······
@xpzero @m-yingyi 

最新版已修复，请更新

**Comment by xpzero** [comment]
> > 更新之后，一片空白，显示：‘无数据，请检查网络或添加基金’，也不能添加基金······
> > @xpzero @m-yingyi
> 
> 最新版已修复，请更新

已恢复，谢谢

**Comment by ICLOUDIRIS** [comment]
可以添加 新债和股票打新的日程提醒嘛

**Comment by AllenL0335** [comment]
目前还是不能添加，不知道是不是我这里屏蔽地址的锅

**Comment by garyxuan** [comment]
> 这样调用api，不怕被告吗？

既然是api就是开放的

**Comment by Realybig** [comment]
还有群吗？

**Comment by huoyuanfan** [comment]
关闭了股票界面后，再也打不开了，请问在哪里可以设置

**Comment by FairyWorld** [comment]
进群微信账号的个性签名显示微信号被封

**Comment by LiuLangQiGai888** [comment]
好像不能支持北交所

**Comment by Termset** [comment]
股票能显示个缩写吗？记代码有点困难

**Comment by leoXuLei** [comment]
微信交流群没法加呀，因为先加的群主微信，但个性签名是已被封号加不上

**Comment by webfunction** [comment]
二维码过期 了

**Comment by 281257120** [comment]
very good

**Comment by bigmgreen** [comment]
希望状态栏的显示可以完全自定义

**Comment by free1990** [comment]
排序不能恢复默认添加顺序了

**Comment by Severn17** [comment]
大佬可以添加债券的支持吗

**Comment by lgln0** [comment]
好多基金没有实时估值的数据

**Comment by CLuCheng** [comment]
可以支持下恒生指数的显示吗?

**Comment by novasky666** [comment]
状态栏股票收益统计可以自定义文本吗？或者增加收益率的显示，一般投资者都不关心持仓收益吧，收益率是最关心的

**Comment by kevinw18** [comment]
你好, 出现了一个报错
fail: HK Stock error https://stock.xueqiu.com/v5/stock/batch/quote.json?

**Comment by liuchengchen1108** [comment]
0830号的版本在最新的vscode上不支持添加自己的自选股票，就是点添加按钮 跳转到搜索栏之后，输入对应的股票名称或者代号没有反应。卸载后再加载也有同样的问题

**Comment by lcbat2** [comment]
希望能支持自定义状态股票名称，自己弄个简写什么的
希望能支持状态栏隐藏或者显示那个图标
希望能支持设置不同的列宽
谢谢！

**Comment by wenjing111** [comment]
希望能支持批量添加，一个个输太慢了，感谢！

**Comment by DaggerToothCaster** [comment]
> 希望能支持批量添加，一个个输太慢了，感谢！

可以直接修改配置文件的，在配置文件中添加
