### ISSUE TITLE
发现盗版vs插件，“果子哥理财”，怎么打击盗版？

### ISSUE THREAD

**Issue by MrBenWang** [LeekHub/leek-fund#191]
这个很明显是盗版，最关键的是，最下面的`交流群` 他贴的是自己的微信二维码。就怕不明真相的韭菜们，被他给骗了。

![果子哥理财盗版](https://user-images.githubusercontent.com/9692054/109454938-65661400-7a90-11eb-8b04-1cdd330693fb.png)

**Comment by giscafer** [comment]
这就很过分了。去给差评一下
