### ISSUE TITLE
与宣传图片严重不符

### ISSUE THREAD

**Issue by SmoothJM** [LeekHub/leek-fund#194]
为什么宣传图片这么红，我的打开后是绿的
宣传图：
![image](https://user-images.githubusercontent.com/44306149/110431652-fb5bf900-80a5-11eb-92ab-97de2b55c78e.png)
我的图：
![image](https://user-images.githubusercontent.com/44306149/110431692-09aa1500-80a6-11eb-9bc5-8061d0e0de30.png)

**Comment by giscafer** [comment]
我想忘记伤痛，你 还截图不是相当于伤口撒盐吗
