### ISSUE TITLE
binance api地址不可用

### ISSUE THREAD

**Issue by hzlawliet** [LeekHub/leek-fund#198]
## Bug Report

 binance api老的地址https://api.binance.com/api/v1/exchangeInfo已不可用，需要从原来的v1修改成v3，如果可以的话是否可以修改成配置项，这样用户可以在settings.json里面自行修改

**Comment by wujunchuan** [comment]
确定不能用吗？我这边可以访问

![image](https://user-images.githubusercontent.com/7511631/111299108-8468c680-868a-11eb-885f-e551969020e0.png)

检查一下网络（代理）等

**Comment by giscafer** [comment]
我这边两个都可以。如果v3结构没啥大变化，可以换成v3的。毕竟新版本可能相对稳定一些

**Comment by giscafer** [comment]
#321
