### ISSUE TITLE
股票排版有问题，股票名称配列不齐

### ISSUE THREAD

**Issue by ideshun** [LeekHub/leek-fund#199]
![image](https://user-images.githubusercontent.com/28327099/111576590-bc3b4f80-87eb-11eb-8e38-cf08054f7d15.png)
建议可以上下拖动调整排序位置，左右拖动名称，金额或者涨跌调整位置。

**Comment by giscafer** [comment]
这个VSCode API 无法支持，不是想html网页那么容易的。
