### ISSUE TITLE
部分股票和指数无法搜索（300848、中证1000）

### ISSUE THREAD

**Issue by yuwanlin** [LeekHub/leek-fund#201]

**Comment by wuxiii** [comment]
貌似新发的股票都无法搜索到

**Comment by iashbringer** [comment]
使用的搜索库似乎比较老，有的股票的名称是老的

**Comment by giscafer** [comment]
测试可以搜到。如果搜不到，请加交易所简称，比如 搜 `300848` 如果没有，就搜 `sz300848`  @wuxiii @iashbringer @yuwanlin
