### ISSUE TITLE
默认折叠没有信息的部分

### ISSUE THREAD

**Issue by xgdgsc** [LeekHub/leek-fund#202]
## Feature Request
 

请描述下这个功能的作用：

  1、这个功能的使用场景是什么？
侧边栏
  2、这个功能解决你的什么问题？
当只使用Stock一栏的时候，每次都要手动折叠Fund，Xueqiu News, Settings
 
希望能设置折叠的栏目，或者默认折叠没有东西的栏目。

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/114012429-e2a75480-9898-11eb-9c9c-455496d0f4ed.png)
编辑器自带功能可以满足你的需求。不想展示的栏目去掉勾选后，日后打开都不会出现
