### ISSUE TITLE
配置文件中去除基金净值信息

### ISSUE THREAD

**Issue by chen86860** [LeekHub/leek-fund#203]
## Feature Request

目前在配置文件会包含当天基金净值信息，会造成多终端同步时配置冲突。如图：

![image](https://user-images.githubusercontent.com/8399882/113718073-deefc280-971e-11eb-80e7-e85740e5974c.png)

考虑将净值信息脱离配置文件，每天根据基金列表同步下基金净值。这样就能解决同步配置冲突的问题。

**Comment by giscafer** [comment]
amount 肯定是存起来的，就是当做数据库来用，不然持仓金额没地方存。没后端只能这样设计。同步这个问题，只留一个 amount 也可能会冲突。目前没有比较好的方案。

编辑器已提醒使用远程的还是本地的合并。这个操作应该能解决问题吧。
