### ISSUE TITLE
fund右上角图片样式错误

### ISSUE THREAD

**Issue by songjiafan** [LeekHub/leek-fund#207]
## Bug Report

Fund栏右上角图标样式错误

## Current Behavior?

图片变大很多

![image](https://user-images.githubusercontent.com/22863991/114667562-2cc58580-9d32-11eb-9923-dc65ab7e3a70.png)

## Steps to reproduce [Optional]

必现

##  Your Environment [Optional]

macos 10.15.7 vscode 1.56.0-insider

**Comment by sujianqingfeng** [comment]
我之前没有得 更新了vscode 就出现了

**Comment by liy9426** [comment]
更新后出现了

**Comment by wujunchuan** [comment]
> 更新后出现了

你们用的是 insider 版本还是正式版。之前在 insider 版本就发现这个问题了 🤣

**Comment by sujianqingfeng** [comment]
![image](https://user-images.githubusercontent.com/16167459/117236898-4a32ce80-ae5c-11eb-919e-7ba7717324d9.png)
正式版吧

**Comment by giscafer** [comment]
新版本是有这个问题

**Comment by DG-King** [comment]
vscode更新最新版就会有问题

**Comment by Reid00** [comment]
+1  vscode 1.56.0 有问题

**Comment by WQMDC** [comment]
+1，看来已经有人提了，就跟个贴

**Comment by jibenziliao** [comment]
+1 vscode 1.56.0 有问题

**Comment by xiaogaofudao** [comment]
更新最新版本 vscode, 同样遇到 +1

**Comment by lxxxv5** [comment]
+1
![image](https://user-images.githubusercontent.com/34152382/117388737-d822be00-af1d-11eb-9e00-7e66cb71c557.png)

**Comment by phone15806516662** [comment]
+1

![image](https://user-images.githubusercontent.com/45963107/117389708-5895ee80-af1f-11eb-8cb8-76b1cc8b7f62.png)

**Comment by JWleo** [comment]
+1，正式版就有这个问题。第一次在github看到回复全是中文的。笑死

**Comment by qiuxiaodu** [comment]
回退到老版本了，这个图标看着难受

**Comment by Corps-Yan** [comment]
https://code.visualstudio.com/updates/v1_55    (･ω<)☆

**Comment by wujunchuan** [comment]
insider 新版本已经修复。

原因是新版删除了缩放图标的逻辑，下个正式版释出后可解，或者我们可以将图标尺寸调整为 `16x16`。

```
// 修复版本
Version: 1.57.0-insider
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T17:37:44.788Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.2.0
```

**Comment by iXingo** [comment]
+1

**Comment by Sakaizd** [comment]
+1

**Comment by iXingo** [comment]
The latest version has fixed this issue, I think we can close it.

**Comment by sujianqingfeng** [comment]
thx

**Comment by giscafer** [comment]
fixed at version v1.9.7
