### ISSUE TITLE
韭菜盒子1.9.7版本，添加基金提示成功，但基金列表仍显示无数据，请检查网络或添加基金

### ISSUE THREAD

**Issue by Colt666** [LeekHub/leek-fund#213]
## 模糊搜索基金，点击后提示添加成功，配置文件中基金代码直接被替换掉了，不应该是追加吗？
![image](https://user-images.githubusercontent.com/42996972/119663827-514e6a80-be65-11eb-8b05-897587bffd64.png)
![image](https://user-images.githubusercontent.com/42996972/119663948-6f1bcf80-be65-11eb-95b2-7e93c2c3a9b9.png)

**Comment by giscafer** [comment]
新鸡吗，最新版本已经新增今年最新几个月的基金。
