### ISSUE TITLE
无法添加基金、股票。左侧一直显示无数据

### ISSUE THREAD

**Issue by yishan33** [LeekHub/leek-fund#220]
fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sh000016,sh000688,hk03690,hk00700,usr_ixic,usr_dji,usr_inx

在添加基金列表里随便点一个是这样的报错

**Comment by giscafer** [comment]
- 开启了VPN或者代理，网络拦截请求不通
- 电脑连接的网络屏蔽了该接口

一般是以上两种原因
