### ISSUE TITLE
能不能适配一下code-server Web版的vscode 这样无法监控流量?

### ISSUE THREAD

**Issue by zhaojinzhou** [LeekHub/leek-fund#222]
## Feature Request

发现在  web版的code-server上的 点击股票详情 没有详情页。
雪球咨询还有 咨询中心都无法使用。

**Comment by giscafer** [comment]
链接发出来看一下

**Comment by zhaojinzhou** [comment]
> 链接发出来看一下
![image](https://user-images.githubusercontent.com/16334836/128170511-4f497e57-6495-41a9-9f34-5ca372188d5a.png)
我自己的 一个 
垃圾服务器 有点慢  请将就看一下。
用的这个  https://github.com/cdr/code-server 官方docker镜像。
http://168.138.214.165:8080/
密码 0b2839580930c6a1be93681c

**Comment by giscafer** [comment]
cmd执行报错了，web端调不出cmd? 这个错误好像是code-server里边的报错。暂还不知道原因

**Comment by Roger1995551** [comment]
需要做一个https访问才可以，需要一套完整的证书。可以参考下面的帖子https://blog.csdn.net/cheng_bian/article/details/127914703
做了https访问之后也只能显示一个趋势图，后面的内容也无法进行显示，因为那些请求都是http请求而非https请求
