### ISSUE TITLE
在vscode安装后，没有自动添加到左侧菜单栏中

### ISSUE THREAD

**Issue by zhangjianye201702** [LeekHub/leek-fund#224]
在vscode安装后，没有自动添加到左侧菜单栏中

韭菜盒子版本：v1.9.9

![image](https://user-images.githubusercontent.com/26397644/129681392-39b533d1-be11-4e46-a142-4680e8a67e9b.png)

![image](https://user-images.githubusercontent.com/26397644/129681648-6e84bf90-9c14-4dfe-945b-87f0aaa4c8a7.png)

**Comment by giscafer** [comment]
是不是隐藏了。建议右键看看是不是

**Comment by zhangjianye201702** [comment]
是隐藏了，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeekHub/leek-fund"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeekHub/leek-fund] 在vscode安装后，没有自动添加到左侧菜单栏中 (#224)





 
是不是隐藏了。建议右键看看是不是
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
