### ISSUE TITLE
侧边栏的股票数据有延迟

### ISSUE THREAD

**Issue by licoba** [LeekHub/leek-fund#225]
## Bug Report

侧边栏的股票数据有延迟

## Current Behavior?

侧边栏的股票数据有延迟，可以看看Stock，没有更新实时的涨跌，点进去看单独每一只股票的涨跌详细图倒是准确的，很实时，只是Sotck栏更新有问题，感觉落后大概有十几分钟
## Expected Behavior?

希望侧边栏的涨跌率能跟上实时的股票涨跌

## Steps to reproduce [Optional]

如上

**Comment by giscafer** [comment]
不可能十几分钟。间隔是3秒。可能网络影响

**Comment by fantasylsdo** [comment]
我使用起来也是十几分钟更新一次。。手动刷新就没有问题。

**Comment by giscafer** [comment]
免费接口是有延迟。
