### ISSUE TITLE
持仓成本和持仓金额问题

### ISSUE THREAD

**Issue by TraCeHe** [LeekHub/leek-fund#227]
![image](https://user-images.githubusercontent.com/44955637/131058637-1279acca-3edd-4732-9b49-5850d5d3bdb1.png)
这个计算是不是有问题,持仓成本3000,得出的百分比-99.99%?

**Comment by giscafer** [comment]
持仓成本是成本价。基金一般都是1~4块之间比较多每次加仓都要改一下

**Comment by giscafer** [comment]
> > 持仓成本是成本价。基金一般都是1~4块之间比较多每次加仓都要改一下
> 
> 大佬，这个成本可以支持直接输原始总金额吗？不然每次都要用计算器根据当前持仓金额和单位净值算下份额，然后再用原始总金额除以份额才能得到 持仓成本 😞

软件自带可以看到啊，不用计算器。比如蚂蚁金服买的基金就可以直接看到持仓成本价

**Comment by 0kk470** [comment]
> > > 持仓成本是成本价。基金一般都是1~4块之间比较多每次加仓都要改一下
> > 
> > 
> > 大佬，这个成本可以支持直接输原始总金额吗？不然每次都要用计算器根据当前持仓金额和单位净值算下份额，然后再用原始总金额除以份额才能得到 持仓成本 😞
> 
> 软件自带可以看到啊，不用计算器。比如蚂蚁金服买的基金就可以直接看到持仓成本价

抱歉眼拙了，支付宝的持仓成本折叠在一个不显眼的灰色箭头下，找了半天 😭

**Comment by nansio** [comment]
> > > > 持仓成本是成本价。基金一般都是1~4块之间比较多每次加仓都要改一下
> > > 
> > > 
> > > 大佬，这个成本可以支持直接输原始总金额吗？不然每次都要用计算器根据当前持仓金额和单位净值算下份额，然后再用原始总金额除以份额才能得到 持仓成本 😞
> > 
> > 
> > 软件自带可以看到啊，不用计算器。比如蚂蚁金服买的基金就可以直接看到持仓成本价
> 
> 抱歉眼拙了，支付宝的持仓成本折叠在一个不显眼的灰色箭头下，找了半天 😭

哈哈哈  看了你们的聊天我也找到了 感谢感谢
