### ISSUE TITLE
我一个朋友说这个名字不好，影响运势，想要换掉这个插件，请问插件有考虑改名字吗？

### ISSUE THREAD

**Issue by WangboBoone** [LeekHub/leek-fund#228]
我一个朋友（不是我自己）说这个名字不好，影响运势，想要换掉这个插件。
他相信玄学，觉得这个插件名字有问题，会影响他的运势，让他亏钱。
替我朋友弱弱的问一下，插件可以改个名字吗？

ps:插件还是很好用的，赞

**Comment by giscafer** [comment]
别买A股运势就来了
