### ISSUE TITLE
连网有问题

### ISSUE THREAD

**Issue by ballyang** [LeekHub/leek-fund#229]
## Bug Report

连网有问题

## Current Behavior?

我用的系统代理 http_proxy时能安装上插件，但打开插件时连不到网。
把系统代理 http_proxy 去掉后就能正常获取数据

##  Your Environment [Optional]

======>>>  lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

===>>> uname -a
Linux ubuntu 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

=====>> vscode 版本
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:43:02.136Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-27-generic

======>>> 韭菜盒子
v1.9.9

**Comment by giscafer** [comment]
是的，翻墙后，接口就请求不到数据。数据源接口网络问题

**Comment by zznature** [comment]
解决了吗？我也是联网有问题。
`fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sh000016,sh000688,hk03690,hk00700,usr_ixic,usr_dji,usr_inx`

macOS 11.1

**Comment by giscafer** [comment]
#16
