### ISSUE TITLE
基金持仓金额设置保存不了

### ISSUE THREAD

**Issue by opensvn** [LeekHub/leek-fund#234]
## Bug Report

基金持仓金额设置保存不了

## Current Behavior?

修改一只基金的持仓成本价和持仓金额后，点击保存按钮，没有任何反应。重新进入设置页面，刚刚编辑的内容没有保存下来，还是旧的数据。

## Expected Behavior?

点击保存按钮会提示保存成功，且数据真正保存下来。

##  Your Environment [Optional]

win10家庭版19043.1237
vscode 版本1.61.0
韭菜盒子 版本2.0.1

**Comment by TinyMaD** [comment]
vscode、韭菜盒子都是最新版还是保存不了，可能跟最近两台电脑数据同步有关

> vscode版本更新到1.61.2可以保存了，韭菜盒子版本未变
