### ISSUE TITLE
个性化设置图标前缀bug

### ISSUE THREAD

**Issue by nyjackielee** [LeekHub/leek-fund#237]
我上班的时候为了看上去不是那么明显所以选择使用纯文本显示，但是第二天我每天重新开启VSCode都会自动重新显示成🍜吃面和🍗鸡腿的图标，我每天都要调一次，心累，心里难受😣
<img width="418" alt="截屏2021-10-28 下午2 27 02" src="https://user-images.githubusercontent.com/22385710/139199052-250346df-7ade-40d2-ac72-2a3d43d81192.png">

<img width="512" alt="截屏2021-10-28 下午2 26 31" src="https://user-images.githubusercontent.com/22385710/139198988-13cec570-f9da-4d18-a97e-92507c1c1196.png">

**Comment by giscafer** [comment]
欢迎PR，应该有存setting才对。有问题的话就是没存到setting，或者读取时没控制吧
