### ISSUE TITLE
股票搜索不到

### ISSUE THREAD

**Issue by hantmac** [LeekHub/leek-fund#238]
## Bug Report

`湖北宜化` 这么火的票在韭菜盒子里搜索不到。
![image](https://user-images.githubusercontent.com/7600925/139386908-1f00329a-297d-4f34-aaab-17080a174ca3.png)

## Current Behavior?

![image](https://user-images.githubusercontent.com/7600925/139386931-c830508b-8de0-412f-ba02-aac411e448a3.png)

正常搜索

##  Your Environment [Optional]

Mac OS

Mac OS

**Comment by giscafer** [comment]
搜 股票代码
