### ISSUE TITLE
新增期货接口

### ISSUE THREAD

**Issue by zxj5470** [LeekHub/leek-fund#239]
## Other reference [Optional]

新浪的期货接口

V2201是期货代码

http://hq.sinajs.cn/list=V2201

**Comment by zxj5470** [comment]
![image](https://user-images.githubusercontent.com/20026798/143686828-b2548d64-d164-4f04-be70-347a523cb58a.png)

🐎的，自己动手丰衣足食

**Comment by giscafer** [comment]
https://github.com/LeekHub/leek-fund/pull/244#issuecomment-982626135 
@zxj5470 看看
