### ISSUE TITLE
可以增加改leek-fund.statusBarStock 股票名称的配置吗？

### ISSUE THREAD

**Issue by Kole6** [LeekHub/leek-fund#243]
可以增加改leek-fund.statusBarStock 股票名称的配置吗？

现在股票直接放在vscode底部还是太明显了，想把名称改成英文的。

**Comment by giscafer** [comment]
原本支持模板，只是还没GUI外放，欢迎PR https://github.com/LeekHub/leek-fund/blob/11725856feea7895e5a9233c0a404fc0203c66fb/src/shared/constant.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L4

**Comment by hustfeather** [comment]
加了此段配置并进行了修改，没有起效果，v2.0.5
