### ISSUE TITLE
搜索不到部分股票信息

### ISSUE THREAD

**Issue by kongyijilafumi** [LeekHub/leek-fund#245]
# 版本信息
vscode版本 v1.62.3
leek-fund版本 v2.0.1

# 无法搜索的股票信息
洪兴股份 001209
同力日升 605286

# 截图
![image](https://user-images.githubusercontent.com/56569970/143801738-5e8ba643-d6fb-4ba4-9b09-01d1589f9131.png)
![image](https://user-images.githubusercontent.com/56569970/143801759-af56f638-f844-43fc-8412-cad49248c9b1.png)
![image](https://user-images.githubusercontent.com/56569970/143801811-738e712c-7fed-45a0-87dd-efacc1f66eb2.png)
![image](https://user-images.githubusercontent.com/56569970/143801825-09692b7d-a622-40cc-823c-bd7712f79d6a.png)

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/143841544-dd86b708-01b3-4d0f-a8fe-315d343db0b3.png)
