### ISSUE TITLE
新增，删除不了股票

### ISSUE THREAD

**Issue by huntlin** [LeekHub/leek-fund#246]
![image](https://user-images.githubusercontent.com/61825325/144369053-a4b4ab23-f6e4-46c0-a5d5-135c579ab116.png)
![image](https://user-images.githubusercontent.com/61825325/144369077-2f90087a-48fd-4f36-abb6-42939b364e50.png)

**Comment by giscafer** [comment]
你这里明显json格式不对。不熟悉使用配置，删除用界面GUI删除。

**Comment by giscafer** [comment]
#23 23
