### ISSUE TITLE
window上vscode内韭菜盒子插件不能显示基金，

### ISSUE THREAD

**Issue by JWleo** [LeekHub/leek-fund#248]
vscode内的插件一直在网络搜索，但是一直没有基金信息的显示，如下图所示：
![image](https://user-images.githubusercontent.com/32316654/145328231-01230003-43f5-45b1-b2ad-000060a5f4c8.png)

**Comment by JWleo** [comment]
韭菜插件版本v2.02,vscode版本是1.63.0,window10

**Comment by JWleo** [comment]
每次打开vscode就显示如下图：
![image](https://user-images.githubusercontent.com/32316654/145328839-d9eb4fdd-1907-4050-9e25-c92a56a23c0b.png)
liunx环境下的基金功能显示又是正常的

**Comment by giscafer** [comment]
> 每次打开vscode就显示如下图： ![image](https://user-images.githubusercontent.com/32316654/145328839-d9eb4fdd-1907-4050-9e25-c92a56a23c0b.png) liunx环境下的基金功能显示又是正常的

这里链接window下浏览器可以打开吗。
两个原因：
- 代理问题
- 域名被墙
