### ISSUE TITLE
fail: Stock error 

### ISSUE THREAD

**Issue by LiuGaoyong** [LeekHub/leek-fund#249]
https://hq.sinajs.cn/list=sh000001,sh000300,sh000016,sh000688,hk03690,hk00700,usr_ixic,usr_dji,usr_inx,sz002250

sina failed???

what this ?

**Comment by giscafer** [comment]
try  tp visiting the url in browser, like below is normal

![image](https://user-images.githubusercontent.com/8676711/145988193-f3f6dd6c-9491-438a-8dc6-0127bb074e8f.png)

#229 

#247 

#16

**Comment by IceApriler** [comment]
报Kinsoku jikou desu

**Comment by hqzh** [comment]
![1694601658160](https://github.com/LeekHub/leek-fund/assets/26128706/2f516aaa-0c85-48cc-8f15-df5faa3ba7d2)
