### ISSUE TITLE
面板FUND 中基金的实时盈亏结果有误

### ISSUE THREAD

**Issue by BBBBeans** [LeekHub/leek-fund#253]
## Bug Report

面板FUND 中基金的实时盈亏结果有误

## Current Behavior?

1.FUND面板基金实则为盈利，但显示为   盈（+-318.89），致使底部状栏统计错误
![image](https://user-images.githubusercontent.com/32087305/147726696-e7c7645d-408a-45fa-9260-a7c8eb61e63f.png)

## Expected Behavior?

1.FUND面板，应为 盈（+318.89）而非 盈（+-318.89）
2.底部状态栏，今日统计也应做相应调整

##  Your Environment [Optional]

VSCode
![image](https://user-images.githubusercontent.com/32087305/147727208-e87d152d-f256-4342-bbf8-e41f1a749bae.png)
韭菜盒子 ：V2.0.2

**Comment by giscafer** [comment]
欢迎调试解决来个PR

**Comment by giscafer** [comment]
#330
