### ISSUE TITLE
无法获取基金数据

### ISSUE THREAD

**Issue by 993576769** [LeekHub/leek-fund#256]
## Bug Report

获取不了股票和基金的数据,浏览器可以访问
已添加新浪接口到v2ray白名单,vscode已设置好proxy

## Current Behavior?

![image](https://user-images.githubusercontent.com/47321107/148870194-7ce7a9d6-72cb-4f0f-89a5-b6cef7d6cc45.png)

##  Your Environment [Optional]

macos 11.6.2

**Comment by giscafer** [comment]
基金走的是 东方财富的。截图是股票接口也走不通。

**Comment by yanghuiqi** [comment]
fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sz399006,hkHSI,hk03690,hk00700,usr_ixic,usr_dji,usr_inx

**Comment by giscafer** [comment]
> > 基金走的是 东方财富的。截图是股票接口也走不通。
> > https://github.com/LeekHub/leek-fund/blob/master/development.md
> 
> @giscafer 我试了一下, 东方财富的接口, 把https改成http就能走通了

有些人确实是 https 有问题，这个以前遇到过。建议多测试一下不同网络环境，比如换WiFi或者连手机热点测试一下。
