### ISSUE TITLE
之前自选的股票看不到了 添加后 也没的了。。是出bug了嘛今天

### ISSUE THREAD

**Issue by czcqwe** [LeekHub/leek-fund#260]

**Comment by wekerSnail** [comment]
我也是

**Comment by chr19960719** [comment]
me too

**Comment by indingpig** [comment]
应该是接口出了问题

**Comment by 1934266584** [comment]
接口403了

**Comment by fank243** [comment]
股票接口是崩了吧，基金还能正常展示数据

![image](https://user-images.githubusercontent.com/44729315/150452650-e80c10b1-93a2-4571-9832-242e771f042c.png)

![image](https://user-images.githubusercontent.com/44729315/150452712-aea20f3a-b1e7-4801-bf6a-74c69e94d4b3.png)

**Comment by kexiaofu** [comment]
今儿凌晨的时候，新浪财经接口加上了 referer 检测， http header 加上 Referer 就可以了

**Comment by Geek-Jokey** [comment]
来个大佬修复一下

**Comment by zhaojianxin1234** [comment]
尴尬了

**Comment by OnlyForYouYaner** [comment]
我也是，以为我的网络出问题了

**Comment by coppyC** [comment]
看不到我的票，难受

**Comment by OnlyForYouYaner** [comment]
> 看不到我的票，难受

我也是，打开手机看又不太方便

**Comment by bigmgreen** [comment]
加1

**Comment by 1934266584** [comment]
![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png)
找到插件源码先自己加上referer，再重启下vscode就行了

**Comment by gittig11** [comment]
参照上面大佬的方法（添加Referer），提了个pr #261

**Comment by cydysm** [comment]
> ![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源码先自己加上referer，再重启下vscode就行了

插件路径为
/.vscode/extensions/giscafer.leek-fund-2.0.4/out/shared/utils.js

vscode 插件安装路径为
-- | --
windows | %USERPROFILE%\.vscode\extensions
macOS | ~/.vscode/extensions
Linux | ~/.vscode/extensions

**Comment by OnlyForYouYaner** [comment]
![image](https://user-images.githubusercontent.com/44225329/150456935-38bbcdbd-267f-471c-8c5f-0e38555b0be4.png)

**Comment by OnlyForYouYaner** [comment]
> ![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源码先自己加上referer，再重启下vscode就行了

好像还是不行，加上了

**Comment by gittig11** [comment]
> > ![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源码先自己加上referer，再重启下vscode就行了
> 
> 好像还是不行，加上了

这样肯定不行，要调试模式。。

**Comment by fank243** [comment]
![1DCA5416](https://user-images.githubusercontent.com/44729315/150457220-4ad1f99d-55bf-4452-a5f8-a6c5836004ba.gif)

**Comment by gittig11** [comment]
> > ![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源码先自己加上referer，再重启下vscode就行了
> 
> 以上文件路径为 .vscode/extensions/giscafer.leek-fund-2.0.4/out/shared/utils.js
> 
> vscode 插件安装路径为 -- | -- windows | %USERPROFILE%.vscode\extensions macOS | ~/.vscode/extensions Linux | ~/.vscode/extensions

直接改插件源码应该也可以。

**Comment by cydysm** [comment]
> > ![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源码先自己加上referer，再重启下vscode就行了
> 
> 好像还是不行，加上了

需要重启vscode

**Comment by Bimbaloo** [comment]
> > > ![图片](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源先自己加上referer，再重启下vscode就行了
> > 
> > 
> > 好像还是不行，加了
> 
> 需要重启vscode

我试了下已经可以了诶
referer: 'https://gu.sina.cn/m/',

**Comment by OnlyForYouYaner** [comment]
> 

刚刚重启了，还没反应过来，现在好了

**Comment by OnlyForYouYaner** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源先自己加上referer，再重启下vscode就行了
> > > 
> > > 
> > > 好像还是不行，加了
> > 
> > 
> > 需要重启vscode
> 
> 我试了下已经可以了诶 referer: 'https://gu.sina.cn/m/',
谢谢大佬，可以了

**Comment by gogosee** [comment]
可以了，哈哈

**Comment by OnlyForYouYaner** [comment]
> > > ![image](https://user-images.githubusercontent.com/25878286/150455044-3064c6af-132e-474c-985c-be1d3918a0af.png) 找到插件源码先自己加上referer，再重启下vscode就行了
> > 
> > 
> > 好像还是不行，加上了
> 
> 需要重启vscode

感觉这两天延迟好高啊，半天反应不过来

**Comment by giscafer** [comment]
欢迎PR

**Comment by JOJOyh** [comment]
有谁知道excel里面怎么添加referer吗？

**Comment by shiyuanzheng** [comment]
加了referer之后 又挂了

**Comment by indingpig** [comment]
> 

我也是，可是postman测试端口有没有问题
