### ISSUE TITLE
新浪接口返回有问题，有没有备用接口？

### ISSUE THREAD

**Issue by kiinlam** [LeekHub/leek-fund#263]
## Current Behavior?

添加股票成功但获取不到数据。

## Expected Behavior?

期望能展示股票实时数据。

## Steps to reproduce [Optional]

![920d4b4dfe274ba7ff69538dc2f5ac1](https://user-images.githubusercontent.com/5861519/150707863-2a94217a-b7fa-4981-8854-7bffe69d9203.png)

新浪接口返回错误的数据，有没有备用的接口？

##  Your Environment [Optional]

windows系统，有线网络，以及手机ios系统，移动网络，都是返回同样的错误数据。

**Comment by dozening** [comment]
坐等修复 好几天看不到数据了

**Comment by giscafer** [comment]
@dozening 最新版本不正常？？。
![image](https://user-images.githubusercontent.com/8676711/150767340-7bb0ba5c-71f8-4284-a06c-6918fe2eaaf7.png)

**Comment by Haiqi-Wu** [comment]
今天好了

**Comment by liuyanchen1994** [comment]
最新版本有这个错误
![image](https://user-images.githubusercontent.com/19524048/150896519-205d77cc-05c4-4037-8c29-14378f118685.png)

**Comment by giscafer** [comment]
> 最新版本有这个错误 ![image](https://user-images.githubusercontent.com/19524048/150896519-205d77cc-05c4-4037-8c29-14378f118685.png)

网络链接超时。

**Comment by liuyanchen1994** [comment]
网页上打开新浪就可以，估计是新浪的服务器问题

**Comment by liuyanchen1994** [comment]
能添加备用的接口地址吗

**Comment by giscafer** [comment]
> 能添加备用的接口地址吗

应该是主力收割资金流出速度影响了新浪服务器。

**Comment by liuyanchen1994** [comment]
> > 能添加备用的接口地址吗
> 
> 应该是主力收割资金流出速度影响了新浪服务器。

你这解释不得不服

**Comment by fanleung** [comment]
同问题，能添加，不可显示

**Comment by liuyanchen1994** [comment]
> 同问题，能添加，不可显示

新浪接口炸了

**Comment by xgdgsc** [comment]
有没有自定义url的功能，这样大家可以用自己的数据源，只要有一个标准格式的预期就行

**Comment by sadofwind** [comment]
Host: hq.sinajs.cn

**Comment by giscafer** [comment]
> hq.sinajs.cn

GraphQL

**Comment by giscafer** [comment]
> 有没有自定义url的功能，这样大家可以用自己的数据源，只要有一个标准格式的预期就行

GraphQL

**Comment by giscafer** [comment]
好像加了referer，已解决
