### ISSUE TITLE
股票接口又不行了

### ISSUE THREAD

**Issue by liuyanchen1994** [LeekHub/leek-fund#264]
![image](https://user-images.githubusercontent.com/19524048/150728749-829b4044-8a77-4e75-9fe9-3015aa69f177.png)
![image](https://user-images.githubusercontent.com/19524048/150728763-d5d5f8a4-9b8a-416b-8ced-e807d40055d0.png)
最新版本又报错了

**Comment by 77yang** [comment]
+1

**Comment by giscafer** [comment]
#16
