### ISSUE TITLE
支持自选股筛选

### ISSUE THREAD

**Issue by Jcanno** [LeekHub/leek-fund#265]
## Feature Request

自选股太多，可以在顶部功能栏增加筛选功能

**Comment by giscafer** [comment]
不建议加。A股不值得投资。
---
欢迎PR

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/172760882-44816917-db59-46be-b17d-1c37372c2bfe.png)
xuanz


VSCode 自带快速定位功能，选中左侧面板任意一个，直接敲键盘就好。目前不支持中文，可以敲股票编号 比如 `600031`
