### ISSUE TITLE
目前不支持港股搜索添加了吗？

### ISSUE THREAD

**Issue by wwyynnn** [LeekHub/leek-fund#266]
## Bug Report

 目前不支持港股hk 添加到自选列表了吗？
## Current Behavior?

举例：添加港股的腾讯控股，hk00700：
![image](https://user-images.githubusercontent.com/29294095/150953853-bcf1655c-fcee-4374-9483-0c6e35d6483f.png)

## Expected Behavior?

期待的操作：应该能搜索出 hk00700 腾讯控股
## Steps to reproduce [Optional]

请见上图

##  Your Environment [Optional]

VS Code
版本: 1.63.2
提交: 899d46d82c4c95423fb7e10e68eba52050e30ba3
日期: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by giscafer** [comment]
#257 

@sungongwei

**Comment by wwyynnn** [comment]
> 

已经修复了？要怎么更新呢

**Comment by giscafer** [comment]
> 已经修复了？要怎么更新呢

搜：Github 怎么参与开源项目开发？Github 怎么提交pr
