### ISSUE TITLE
持仓金额保存失败

### ISSUE THREAD

**Issue by Jane-blog** [LeekHub/leek-fund#274]
win10系统 ，持仓金额保存失败

**Comment by lavenderfly** [comment]
![image](https://user-images.githubusercontent.com/100327491/155909575-91d5682a-abc0-464c-9f69-e86f8082d29e.png)
the msg when click save

**Comment by giscafer** [comment]
个人试了没重现，建议尝试调试看问题 https://github.com/LeekHub/leek-fund/blob/b867041aaf5360fe7990158eb6bc805f0351b4a1/template/fund-amount.html#L482

**Comment by binscor** [comment]
leek-fund.fundAmount | 基金持仓金额（不建议手填，格式错误影响功能） | [object Object]

这个后面的对象需要的属性格式啥的能否给个示例，界面保存不了，手动写进settings也行，感谢

**Comment by binscor** [comment]
经过调试，在请求这个数据的时候，
https://fundmobapi.eastmoney.com/FundMNewApi/FundMNFInfo?pageIndex=1&pageSize=6&plat=Android&appType=ttjj&product=EFund&Version=1&deviceid=3f86bcc2a70dff37blijsvv&Fcodes=320007

Expansion返回null

**Comment by gittig11** [comment]
存在这个bug，原因是接口

**Comment by gittig11** [comment]
存在这个bug，原因是接口`https://fundmobapi.eastmoney.com/FundMNewApi/FundMNFInfo`添加了user-agent校验。

提了个pr #278
