### ISSUE TITLE
基金删除失败

### ISSUE THREAD

**Issue by zrk1997** [LeekHub/leek-fund#275]
![图片](https://user-images.githubusercontent.com/45419058/155913234-5e4bd247-cbe7-4a3a-a8f4-3580ed4c8698.png)

**Comment by giscafer** [comment]
try again

**Comment by zrk1997** [comment]
> try again

还是不行

**Comment by giscafer** [comment]
我试了可以，2.0.5

**Comment by zrk1997** [comment]
> 我试了可以，2.0.5

![图片](https://user-images.githubusercontent.com/45419058/156089430-85ccce97-4778-4393-ad32-898114668be6.png)
我早上还是这样，有没有什么重置的办法

**Comment by zrk1997** [comment]
> 我试了可以，2.0.5

![图片](https://user-images.githubusercontent.com/45419058/156089536-af294591-c9de-46a0-ba3a-a56b60a333c5.png)
添加基金显示增加成功了，但是页面没有任何显示

**Comment by zrk1997** [comment]
> 

有没有什么办法解决

**Comment by James-chok** [comment]
> > 
> 
> 有没有什么办法解决

可以提供一下基金代码让我看一下吗？
另外，`target`是`VSCode`传过来的，所以出现`undefined`的情况，我们也决定不了。或者让老哥看一下 @giscafer 。

**Comment by zrk1997** [comment]
> > > 
> > 
> > 
> > 有没有什么办法解决
> 
> 可以提供一下基金代码让我看一下吗？ 另外，`target`是`VSCode`传过来的，所以出现`undefined`的情况，我们也决定不了。或者让老哥看一下 @giscafer 。

![图片](https://user-images.githubusercontent.com/45419058/159829056-bff738ae-e318-4881-a59e-9d3049da69e8.png)
所有基金都删除失败

**Comment by James-chok** [comment]
> > > > 
> > > 
> > > 
> > > 有没有什么办法解决
> > 
> > 
> > 可以提供一下基金代码让我看一下吗？ 另外，`target`是`VSCode`传过来的，所以出现`undefined`的情况，我们也决定不了。或者让老哥看一下 @giscafer 。
> 
> ![图片](https://user-images.githubusercontent.com/45419058/159829056-bff738ae-e318-4881-a59e-9d3049da69e8.png) 所有基金都删除失败

试一下新建一个分组，然后把这些基金添加到新的分组，最后再把`我的基金`分组删掉

**Comment by zrk1997** [comment]
> 

还是没有，想放弃了

**Comment by James-chok** [comment]
> > 
> 
> 还是没有，想放弃了

在`settings.json`中，截图一下`leek-fund.funds`和`leek-fund.fundGroups`的信息看一下？

**Comment by zrk1997** [comment]
> > > > 
> > > 
> > > 
> > > 有没有什么办法解决
> > 
> > 
> > 可以提供一下基金代码让我看一下吗？ 另外，`target`是`VSCode`传过来的，所以出现`undefined`的情况，我们也决定不了。或者让老哥看一下 @giscafer 。
> 
> ![图片](https://user-images.githubusercontent.com/45419058/159829056-bff738ae-e318-4881-a59e-9d3049da69e8.png) 所有基金都删除失败

![图片](https://user-images.githubusercontent.com/45419058/159835563-36c04af1-684c-470e-9400-5702c7984c87.png)

**Comment by James-chok** [comment]
你提供的这几个基金确实会有问题😂  ，但是好像跟这里的基金不一样。 ![photo](https://user-images.githubusercontent.com/45419058/159829056-bff738ae-e318-4881-a59e-9d3049da69e8.png)

**Comment by giscafer** [comment]
> 可以提供一下基金代码让我看一下吗？ 另外，`target`是`VSCode`传过来的，所以出现`undefined`的情况，我们也决定不了。或者让老哥看一下 @giscafer 。

这个问题之前一直有，不过是偶发的。不会每次都能重现吧？

**Comment by James-chok** [comment]
> > 可以提供一下基金代码让我看一下吗？ 另外，`target`是`VSCode`传过来的，所以出现`undefined`的情况，我们也决定不了。或者让老哥看一下 @giscafer 。
> 
> 这个问题之前一直有，不过是偶发的。不会每次都能重现吧？

很容易重现，譬如连续点击基金的置顶按钮，但是不会每次。

**Comment by giscafer** [comment]
这里的target 为空，目前不知道去哪找这个target了，拿不到id就删除不了。

**Comment by James-chok** [comment]
> 这里的target 为空，目前不知道去哪找这个target了，拿不到id就删除不了。

是的，所以我感觉这个问题暂时无解

**Comment by James-chok** [comment]
> 这里的target 为空，目前不知道去哪找这个target了，拿不到id就删除不了。

还有一种可能，刷新的时候请求数据用了await，不确定是不是由这个引起。
