### ISSUE TITLE
基金预估收益有问题

### ISSUE THREAD

**Issue by Autoimaxxer** [LeekHub/leek-fund#291]
## Bug Report

基金持仓金额设置页面无法刷新预估总收益
## Current Behavior?

基金持仓金额设置页面底部有一个预估收益，第一次打开此页面时，底部预估收益是正确的，但是随着股市波动，基金预估收益也会随之波动，正常点击右上角刷新按钮会刷新收益，但是现在点击刷新无效，还是停留在第一次打开时候的预估收益。需要重启vscode然后再次打开基金持仓金额设置页面才会正确显示预估收益。

## Expected Behavior?

应该在刷新的时候会实时计算出当前基金预估收益，此前版本无问题，此次更新出现的问题。
## Steps to reproduce [Optional]

目前不清楚什么问题导致的。

##  Your Environment [Optional]

win10系统，vscode为1.65.2版本

**Comment by giscafer** [comment]
@James-chok

**Comment by James-chok** [comment]
Got it.
