### ISSUE TITLE
韭菜之家 =>我的自选一直显示loading

### ISSUE THREAD

**Issue by iarjian** [LeekHub/leek-fund#294]
## Bug Report

韭菜之家 =>我的自选一直显示loading

## Current Behavior?

更新至2.1.0后续版本出现 2.1.0之前的版本显示正常

## Expected Behavior?

应该数据正常加载 可进行价格预警

##  Your Environment [Optional]

windows 10 ,vscode 版本1.65.2

**Comment by James-chok** [comment]
[TypeError: Converting circular structure to JSON --> starting at object with constructor 'ClientRequest'](https://stackoverflow.com/questions/64735881/typeerror-converting-circular-structure-to-json-starting-at-object-with-con)
