### ISSUE TITLE
港股更新慢, 数据还滞后

### ISSUE THREAD

**Issue by dhlie** [LeekHub/leek-fund#296]
港股更新慢,数据滞后(看到的是几分钟前的成交价), 希望优化下

**Comment by giscafer** [comment]
目前 东方财富接口是这样的，应该是，接口方知道别人调用，用的是缓存提供数据。

**Comment by James-chok** [comment]
[港股的LV2到底有什么作用？](https://m.gelonghui.com/p/164308)

**Comment by dhlie** [comment]
> 

比东方财富自选股延迟15分钟, 感觉不太正常啊, 都没有港股Level2

**Comment by James-chok** [comment]
> > 
> 
> 比东方财富自选股延迟15分钟, 感觉不太正常啊, 都没有港股Level2

左边的股票数据用的是新浪，点击股票打开的走势图用的是东方财富。

**Comment by giscafer** [comment]
此问题可以参考 https://github.com/zhangxiangliang/stock-api  来改进。历史问题
