### ISSUE TITLE
3-29无法打开插件

### ISSUE THREAD

**Issue by nmnmtttt** [LeekHub/leek-fund#301]
![image](https://user-images.githubusercontent.com/34001432/160516169-01ff8585-3f8d-455c-b065-306e1e629f04.png)

点击持仓情况报这个情况，发生什么事了

**Comment by James-chok** [comment]
更新插件试一下

**Comment by zhu99899** [comment]
一样的问题,更新切换版本,卸载重装都不可以

**Comment by James-chok** [comment]
> 一样的问题,更新切换版本,卸载重装都不可以

不能进 `基金持仓金额设置` 还是 `韭菜中心`？

**Comment by zhu99899** [comment]
> > 一样的问题,更新切换版本,卸载重装都不可以
> 
> 随便添加几个基金，然后再试一下。

发现了问题的原因,在使用中断网的话leek-fund.funds会被清空,就导致不能正常显示

**Comment by James-chok** [comment]
> > > 一样的问题,更新切换版本,卸载重装都不可以
> > 
> > 
> > 随便添加几个基金，然后再试一下。
> 
> 发现了问题的原因,在使用中断网的话leek-fund.funds会被清空,就导致不能正常显示

`2.3.1` 应该不会再有这个问题

**Comment by nmnmtttt** [comment]
更新到 2.3.1 可以正常当韭菜了，谢谢作者耐心回答。
