### ISSUE TITLE
个人觉得增加这两个功能能大大提高使用体验

### ISSUE THREAD

**Issue by leoXuLei** [LeekHub/leek-fund#310]
1. 股票自定义分组，目前添加的股票都在A Stock下面，数量太多了，如果能自定义分组，按照行业、概念、题材，会清晰很多
2. 股票实时走势，目前5分钟到60分钟都有选项，但是缺少120分钟，60分钟和120分钟的使用频率远高于5分钟、15分钟

**Comment by James-chok** [comment]
Group0
|_______A Stock
|_______HK Stock
|_______US Stock
|_______CN Future
Group1
|_______A Stock
|_______HK Stock
|_______US Stock
|_______CN Future
Group2
|_______A Stock
|_______HK Stock
|_______US Stock
|_______CN Future

**Comment by giscafer** [comment]
- 对于第2点：实时走势是iframe内嵌网页的，非自己开发。
- 对于第1点：
如上 @James-chok 列的，支持自定义会显得目录更乱，并且还有置顶功能。建议这个东西在设计 沟通清楚再着手写代码。

**Comment by James-chok** [comment]
> * 对于第2点：实时走势是iframe内嵌网页的，非自己开发。
> * 对于第1点：
>   如上 @James-chok 列的，支持自定义会显得目录更乱，并且还有置顶功能。建议这个东西在设计 沟通清楚再着手写代码。

现在的股票已经自带分组，再分组就比较复杂。

**Comment by giscafer** [comment]
> > * 对于第2点：实时走势是iframe内嵌网页的，非自己开发。
> > * 对于第1点：
> >   如上 @James-chok 列的，支持自定义会显得目录更乱，并且还有置顶功能。建议这个东西在设计 沟通清楚再着手写代码。
> 
> 现在的股票已经自带分组，再分组就比较复杂。

实现复杂啰嗦，使用上体验也不会很好了。正常是不建议用插件添加那么多股票关注呀。。。

有必要的话 后期加个持仓置顶高亮，持仓统一顶部功能显示就好了。

**Comment by leoXuLei** [comment]
> 

股票分组自定义分组确实比较复杂，但是这样会不会简单一些：股票列表在不排序情况下支持拖拽移动某个股票，不行的话右键支持上移下移也行，置顶只是移到列表顶部达不到这样灵活的效果。

**Comment by James-chok** [comment]
> > 
> 
> 股票分组自定义分组确实比较复杂，但是这样会不会简单一些：股票列表在不排序情况下支持拖拽移动某个股票，不行的话右键支持上移下移也行，置顶只是移到列表顶部达不到这样灵活的效果。

vscode插件有望支持拖拽功能
[https://github.com/Microsoft/vscode/issues/32592](url)

**Comment by giscafer** [comment]
拖拽已经有 demo了，拖拽还得限制不能拖到别的地方。不然数据就乱了，没细看，不知道方不方便限制。数据结构变动大就不建议。https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/testViewDragAndDrop.ts

相比，不如右键上下移动数组元素位置实现方便，数据结构也不用变。

**Comment by James-chok** [comment]
> 

可以直接在现在的置顶按钮旁边增加上移和下移两个按钮吗？那就不用右键了。

**Comment by giscafer** [comment]
> 可以直接在现在的置顶按钮旁边增加上移和下移两个按钮，那就不用右键了。

嗯。右键不是很方便。目前的tree item 按钮不多，还可以放

**Comment by leoXuLei** [comment]
> > 可以直接在现在的置顶按钮旁边增加上移和下移两个按钮，那就不用右键了。
> 
> 嗯。右键不是很方便。目前的tree item 按钮不多，还可以放

👍稳！
