### ISSUE TITLE
股票升序倒序 有问题

### ISSUE THREAD

**Issue by fzziii** [LeekHub/leek-fund#311]
股票倒序、升序有问题，虽然影响不大，但请知吧
![image](https://user-images.githubusercontent.com/39999647/163512008-249f6095-07de-497a-b877-2fefbc66d425.png)

**Comment by fzziii** [comment]
上面是按照跌的 降序排；

下面这个是按涨的 降序排 也有问题
![image](https://user-images.githubusercontent.com/39999647/163512162-7ce2883f-6e57-45cb-9b86-c2b8280e8674.png)

**Comment by giscafer** [comment]
这个按钮有三个功能：
- 正常顺序（含置顶，置顶会一直在头部）
- 升序
- 降序
点击的时候是这三种情况切换的，之前是一直没问题的。

**Comment by fzziii** [comment]
现在的确出了bug哦，这个功能也一直在用的，也知道有这三个功能。但现在升序或者降序 都会乱的，可能是特定场景出现的？

**Comment by giscafer** [comment]
@fzziii 我试了试正常的。是最新版本吧？

**Comment by fzziii** [comment]
是的，当前降序排的 也还是有问题。升序也是有问题的
![image](https://user-images.githubusercontent.com/39999647/163748982-1053287c-1fb4-4924-b369-8219f840138a.png)
![image](https://user-images.githubusercontent.com/39999647/163749119-868b9ed9-1bea-4d05-8b7b-a95e50417cae.png)

**Comment by giscafer** [comment]
你确定第一个框的股，没有设置置顶？建议你把配置文件的 leekfund.stock 数据也粘贴出来看看

**Comment by giscafer** [comment]
> 这个按钮有三个功能：
> 
> * 正常顺序（含置顶，置顶会一直在头部）
> * 升序
> * 降序
>   点击的时候是这三种情况切换的，之前是一直没问题的。

答案
