### ISSUE TITLE
基金预期收益的更新存在问题 - 一个周期被多次刷新出不一致的值

### ISSUE THREAD

**Issue by serfend** [LeekHub/leek-fund#315]
## Current Behavior?
![录制_2022_04_26_12_56_54_97](https://user-images.githubusercontent.com/20139227/165227552-12648c46-1b3f-4c13-8761-c1458f00733b.gif)

## Expected Behavior?
其数值不应该反复横跳

## Steps to reproduce [Optional]
1. 打开基金列表，添加多个基金
2. 多次修改基金列表，并保存
3. 可以发现预期收益的值将出现每个周期多次调用`updateFundBarItem`方法，且数据来源不一致

**Comment by giscafer** [comment]
这个有可能是后边调整影响了。 需要排查一下。

**Comment by James-chok** [comment]
是不同分组里面会有相同的基金代码吗？

**Comment by James-chok** [comment]
![截屏2022-04-26 15 50 53](https://user-images.githubusercontent.com/21700100/165249720-3d63c4a0-c7fb-4a3c-a49e-ddfa3850a203.png)

totalProfit totalAmount 需要作为全局变量
