### ISSUE TITLE
基金持仓信息设置

### ISSUE THREAD

**Issue by way-program** [LeekHub/leek-fund#317]
想请教下在设置基金持仓信息中，持仓金额是指的什么意思？是持仓份额还是持有金额？

**Comment by giscafer** [comment]
持仓金额就是基金目前`持有金额`。持仓成本价是`金额/份额`

**Comment by guestccc** [comment]
> 持仓金额就是基金目前`持有金额`。持仓成本价是`金额/份额`

那其实你说的`持有金额`，应该不是APP的持有金额，而是`持仓成本金额`（持有份额*持仓成本价）
