### ISSUE TITLE
数据刷新有问题

### ISSUE THREAD

**Issue by yanghuiqi** [LeekHub/leek-fund#322]
![image](https://user-images.githubusercontent.com/28619583/172559178-caccb69a-0988-4989-b0df-f9881f1ab2ab.png)
fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sz399006,hkHSI,hk03690,hk00700,usr_ixic,usr_dji,usr_inx
接口坏了，基金数据不刷新了，导致空白

**Comment by James-chok** [comment]
> fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sz399006,hkHSI,hk03690,hk00700,usr_ixic,usr_dji,usr_inx
接口坏了，基金数据不刷新了，导致空白

这个是股票数据请求失败，并且这里面有港股数据，是不是用的旧版本？因为港股现在都用雪球的数据源。

股票数据请求失败意味着网络有点问题？所以基金也不显示了。

**Comment by giscafer** [comment]
新浪的接口有个特点。全局开了VPN大多数情况就挂的。

**Comment by yanghuiqi** [comment]
> > fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sz399006,hkHSI,hk03690,hk00700,usr_ixic,usr_dji,usr_inx
> > 接口坏了，基金数据不刷新了，导致空白
> 
> 这个是股票数据请求失败，并且这里面有港股数据，是不是用的旧版本？因为港股现在都用雪球的数据源。
> 
> 股票数据请求失败意味着网络有点问题？所以基金也不显示了。

是最新版本，不知道咋回事了，

**Comment by yanghuiqi** [comment]
![image](https://user-images.githubusercontent.com/28619583/172978156-2944fab0-d302-4e68-ac29-77e8e4cf11e0.png)
基金，和港股这两个数据就有问题，一直不显示。

**Comment by giscafer** [comment]
@yanghuiqi 是不是存在非法code。建议去配置文件复制 插件的配置贴出来，方便排查

**Comment by yanghuiqi** [comment]
"leek-fund.funds": [
    [
      "005063",
  ]
  ],
  "leek-fund.fundSort": -1,
就这几行，我卸载好多次，重装好多次

**Comment by giscafer** [comment]
@yanghuiqi 手机4G热点试一下？协助排查。确认VPN不要开启

**Comment by yanghuiqi** [comment]
公司自带vpn，可能影响了？
