### ISSUE TITLE
Stock选项不见了

### ISSUE THREAD

**Issue by dino9999** [LeekHub/leek-fund#327]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/108166598/175757525-bc906250-5386-407a-931d-c48b05fa3c7b.png">
基金选择和设置都存在 但是stock就不见了

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/181711138-d690e728-b70c-4dff-ab0a-187a009a2231.png)
这里没有？
