### ISSUE TITLE
状态栏无法选股

### ISSUE THREAD

**Issue by huanghaowen372** [LeekHub/leek-fund#331]
## Bug Report

状态栏无法选股

## Current Behavior?

状态栏默认显示上证指数，修改股票后状态栏消失，设置里的隐藏股票状态栏显示为true，修改后状态栏还是显示的上证指数

## Steps to reproduce [Optional]

选股前：![image](https://user-images.githubusercontent.com/43602502/178173953-4844ff53-1670-4e28-9a49-eb89c90090a8.png)
选股后：![image](https://user-images.githubusercontent.com/43602502/178174001-450fa0b9-6eb2-4910-ba50-abdd52ecb892.png)

##  Your Environment [Optional]

突然发生的，我想和系统也没什么关系吧，但还是贴一下
![image](https://user-images.githubusercontent.com/43602502/178174100-e5cb0786-625d-47ec-a9eb-9533ee720175.png)

**Comment by giscafer** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/8676711/178531101-e20854a8-ec58-4196-9ca0-983717d75ca3.png">
我看正常呢，问问别的网友？
