### ISSUE TITLE
部分指数版面都变成个股版面了，看不到多少涨跌

### ISSUE THREAD

**Issue by xArbiterx** [LeekHub/leek-fund#344]
目测观察到的有深证成指399001  创业板指 399006 国证2000 399303

**Comment by giscafer** [comment]
具体说一下。看看是不是和这个有关 https://github.com/LeekHub/leek-fund/pull/336

**Comment by xArbiterx** [comment]
> 具体说一下。看看是不是和这个有关 #336

看着是有关，正常的指数版面都是老的样式

**Comment by giscafer** [comment]
> > 具体说一下。看看是不是和这个有关 #336
> 
> 看着是有关，正常的指数版面都是老的样式

截个图看看。我很久不用了。

**Comment by iarjian** [comment]
> 具体说一下。看看是不是和这个有关 #336

这里只排除了上证指数的代码  深证的没有做排除 我加一下
