### ISSUE TITLE
个股分时延迟严重

### ISSUE THREAD

**Issue by xArbiterx** [LeekHub/leek-fund#349]
## Current Beha
![Snipaste_2022-09-09_10-06-23](https://user-images.githubusercontent.com/20737805/189257227-4a1860e1-b9a4-4712-ba27-68512c4279a3.png)
vior?

**Comment by giscafer** [comment]
不登录就这样的。这是官方的web 页面，iframe嵌入的。

**Comment by xArbiterx** [comment]
> 不登录就这样的。这是官方的web 页面，iframe嵌入的。
以前不这样的

**Comment by giscafer** [comment]
@iarjian https://github.com/LeekHub/leek-fund/pull/336/files  跟进一下？

**Comment by iarjian** [comment]
> 
节后开盘看一下,这个是嵌入的官方的  实在延迟到时候就还原到以前的了

**Comment by iarjian** [comment]
> @iarjian https://github.com/LeekHub/leek-fund/pull/336/files 跟进一下？

恢复到以前的了   看了下官方新的分时图是延迟比较大
