### ISSUE TITLE
价格预警失效了

### ISSUE THREAD

**Issue by iarjian** [LeekHub/leek-fund#350]
## Bug Report

价格预警失效了

**Comment by Kole6** [comment]
有这个功能吗，怎么用？

**Comment by iarjian** [comment]
![image](https://user-images.githubusercontent.com/28347543/224595576-1fabdddc-f1ed-44fa-81b0-684f69cc13d8.png)

**Comment by Kole6** [comment]
刚刚试了一下这个价格预警，设置了A股的股票涨跌到多少价格，刷新价格等待到了设定值之后，确实不会收到通知

**Comment by iarjian** [comment]
设置里面的提醒要打开
![image](https://user-images.githubusercontent.com/28347543/224598387-fb424470-447a-4edf-96c9-db4986f892cf.png)

**Comment by giscafer** [comment]
预警默认打开的，目前确实没有一个全局的可视化操作开启预警和关闭预警，到配置里边看是不太方便。欢迎PR
