### ISSUE TITLE
功能突然不见了

### ISSUE THREAD

**Issue by MiracleDragon** [LeekHub/leek-fund#352]
之前能看到筹码分布的，还有买1买2买3..等的信息，怎么后面突然又没了。。。😳

**Comment by MiracleDragon** [comment]
![image](https://user-images.githubusercontent.com/43160759/196839041-9a3b1d5e-4a41-4089-8c0a-eafc828febc7.png)
之前这一的地方是能看筹码峰的，后面不知道为什么就不见了
![image](https://user-images.githubusercontent.com/43160759/196839185-6864d868-e403-4f56-b703-8e57dbb76f50.png)
这边之前有一段时间有买1买2买3卖1卖2卖3等信息的，现在也木有了。。。

**Comment by giscafer** [comment]
最新版吗？最近可没发布过，可能是官方调整了， 这是 iframe嵌入的页面

**Comment by MiracleDragon** [comment]
我以为是你们自己开发的去掉了😂原来是嵌入的😂

**Comment by giscafer** [comment]
> 我以为是你们自己开发的去掉了😂原来是嵌入的😂
可以开发，但没必要。何必重复造轮子。
