### ISSUE TITLE
休市自动关闭 

### ISSUE THREAD

**Issue by shunhua** [LeekHub/leek-fund#358]
是否能加上休市自动关闭 的功能？
比如：可以设置几点到几点显示/关闭 状态栏，

**Comment by giscafer** [comment]
> 是否能加上休市自动关闭 的功能？
> 
> 比如：可以设置几点到几点显示/关闭 状态栏，

代码逻辑有休市自动停止轮休请求接口

**Comment by giscafer** [comment]
不考虑扩展。
