### ISSUE TITLE
请求新浪链接已经403

### ISSUE THREAD

**Issue by qq516249940** [LeekHub/leek-fund#359]
请求新浪链接已经403
https://hq.sinajs.cn/list=hk00700
请问还有请求地址吗，还有是如何更换地址。
![image](https://user-images.githubusercontent.com/19165935/200989159-9b82cff8-7a02-4806-b1c7-53aeb7534f30.png)

**Comment by giscafer** [comment]
看 developer.md 文档

**Comment by giscafer** [comment]
#165

**Comment by James-chok** [comment]
公司网墙了？

**Comment by giscafer** [comment]
这个地址我也访问不了，待观察

**Comment by qq516249940** [comment]
In [13]: import requests

In [14]: headers={'Referer' :'https://finance.sina.com.cn'}
    ...: url='https://hq.sinajs.cn/list=sh600000'
    ...: file=requests.get(url=url,headers=headers)
    ...: print(file.text)
var hq_str_sh600000="浦发银行,6.830,6.780,6.940,6.980,6.830,6.940,6.950,40237053,277525770.000,71208,6.940,278600,6.930,136200,6.920,133700,6.910,261400,6.900,283009,6.950,781217,6.960,817835,6.970,902872,6.980,1002106,6.990,2022-11-11,15:00:00,00,";
![image](https://user-images.githubusercontent.com/19165935/201483565-52c6aac8-9687-4742-8807-dd43dd4e194a.png)


我使用python3 添加Referer可以访问了， Referer 是一个常见字段，提供访问来源的信息。
来源：https://www.jisilu.cn/question/449813  请各位大佬参考一下。

**Comment by wdwate** [comment]
666
