### ISSUE TITLE
打开插件一段时间后stock快速刷新（一秒大概五六次），导致cpu飙升

### ISSUE THREAD

**Issue by jsonchen136** [LeekHub/leek-fund#365]
## Bug Report

打开插件一段时间后stock快速刷新（一秒大概五六次），导致cpu飙升，需要重启vscode才行，每天打开插件后100%会出现。

操作系统：win10
插件版本：2.9.4

**Comment by giscafer** [comment]
问题可能是存在的。后边的pr没细看，可能有些写法有问题。

**Comment by giscafer** [comment]
#447 #446
