### ISSUE TITLE
CN_Future 分类中，黄金期货无法正确显示百分比

### ISSUE THREAD

**Issue by yanboer** [LeekHub/leek-fund#368]
## Bug Report

![image](https://user-images.githubusercontent.com/48461101/219254989-f00d46ae-a743-411b-9dc5-b481963bea11.png)

CN_Future 中，添加 黄金连续 期货后，无法正确显示百分比。

## Current Behavior?

CN_Future 中，添加 黄金连续 期货后，无法正确显示百分比。

##  Your Environment [Optional]

版本信息：
![image](https://user-images.githubusercontent.com/48461101/219255225-73c6067f-dbc0-4d73-9887-d72f1b785c22.png)

**Comment by zxj5470** [comment]
https://github.com/LeekHub/leek-fund/pull/380

可以修复这个问题了
