### ISSUE TITLE
状态栏添加时间

### ISSUE THREAD

**Issue by hardmanhong** [LeekHub/leek-fund#369]
状态栏添加时间，不用经常性去关注电脑右下角的时间，因为需要关注休盘时间

**Comment by giscafer** [comment]
没必要呀。本身插件也不是为了盯盘的。偶尔看看。想看时间OUTPUT有实时新闻也满足了
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/8676711/219839469-11ee49f7-60cd-452a-97fb-b849bcf2e946.png">

**Comment by zuibunan** [comment]
@giscafer 
![image](https://user-images.githubusercontent.com/3386786/220143409-5df61c34-ca96-4be3-9bb9-ee33cd985dc2.png)

suggestion:
statusBarTooltip
add last update time, trade amount
or add statusBarTooltipFormat config ?

**Comment by giscafer** [comment]
@zuibunan 这里确实可以加个时间。欢迎PR

**Comment by giscafer** [comment]
v3.0.4 已支持
