### ISSUE TITLE
怎么侧边栏看不到股票自选只有基金，而编辑器下面可以看（不知道按了什么变这样了）

### ISSUE THREAD

**Issue by wuweiyuan** [LeekHub/leek-fund#379]
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/36296284/234740376-206691e2-2242-4cdf-a359-726b2f83b080.png">

**Comment by giscafer** [comment]
#229 是否用了全局代理？

**Comment by wuweiyuan** [comment]
> #229 是否用了全局代理？

我把代理去掉了也不行，是能获取股票的数据的，只是侧边栏弄不回来了

**Comment by giscafer** [comment]
卸载重装试试吧，因为你这么描述页定位不了问题。或者你试试打开开发者工具看看。
<img width="807" alt="image" src="https://github.com/LeekHub/leek-fund/assets/8676711/45629778-19db-4c3d-a0f2-0ef59709662e">
