### ISSUE TITLE
不同窗口状态栏顺序乱了

### ISSUE THREAD

**Issue by xgdgsc** [LeekHub/leek-fund#382]
## Bug Report

 不同窗口状态栏股票顺序乱了

## Current Behavior?
不同窗口状态栏股票顺序乱了，没有按配置文件里的顺序

## Expected Behavior?

所有窗口状态栏股票顺序按配置文件里statusBarStock的顺序一致

 
##  Your Environment [Optional]
 
Ubuntu 2204 kde， latest vscode

**Comment by giscafer** [comment]
股票栏有排序功能，看看是否是点击了排序
