### ISSUE TITLE
基金不能显示了

### ISSUE THREAD

**Issue by hongyi1159** [LeekHub/leek-fund#387]
fundService.js的69行
const time = item.GZTIME?.substr(0, 10);   这行代码现在的 GZTIME 是null了

**Comment by James-chok** [comment]
其实没有用，主要是没有数据返回了。

**Comment by chen86860** [comment]
据说要下线实时估值功能，哎

https://www.sohu.com/a/691743109_121108317

**Comment by VJoer** [comment]
基金国家规定不能返回估值，但是目前来看wind还可以看到基金估值

**Comment by giscafer** [comment]
fixed at v[3.3.1](https://github.com/LeekHub/leek-fund/commit/1881c556bf8103693b4ef5434fcf729bcc43fb96)

**Comment by MissDelia** [comment]
升级到了3.3.1似乎并没有解决问题，fund还是空的

**Comment by Cloudkkk** [comment]
> 升级到了3.3.1似乎并没有解决问题，fund还是空的

+1
