### ISSUE TITLE
更新3.3.1，底部状态栏基金无法正常显示，侧栏基金仅显示表头，无法点开明细

### ISSUE THREAD

**Issue by JGX19** [LeekHub/leek-fund#389]
![image](https://github.com/LeekHub/leek-fund/assets/36809606/17e81179-a99b-41a5-8eb9-d96d53c3983c)
![image](https://github.com/LeekHub/leek-fund/assets/36809606/210eb58d-04da-408c-bbe8-c3a1227a3b1f)
json文件如下：
{
    "workbench.colorTheme": "Default Dark+",
    "workbench.iconTheme": "vscode-icons",
    "security.workspace.trust.untrustedFiles": "open",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "workbench.colorCustomizations": {
    
    },
    // tab一键生成标签
    "emmet.triggerExpansionOnTab": true,
    "fileheader.cursorMode": {
    
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "vsicons.dontShowNewVersionMessage": true,
    "[vue]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "Codegeex.Privacy": false,
    "Codegeex.Explanation.LanguagePreference": "zh-CN",
    "Codegeex.EnableExtension": false,
    "stock-watch.stocks": [
    
        "sh000001",
        "hkHSI",
        "hkHSTECH",
    ],
    "leek-fund.funds": [
        [
            "012348",
            "000071",
            "001180",
            "160119",
            "013395",
            "002656",
            "100032",
            "000248",
            "110020",
            "000968"
        ]
    ],
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "explorer.confirmDelete": false,
    "[handlebars]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "leek-fund.hideStatusBarStock": false,
    "leek-fund.statusBarStock": [
        "sh000001"
    ],
    "leek-fund.fundSort": 2,
    "leek-fund.fundAmount": {

        "100032": {
            "name": "富国中证红利指数增强A",
            "amount": 1000,
            "price": "0.9940",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "110020": {
            "name": "易方达沪深300ETF联接A",
            "amount": 1000,
            "price": "1.4639",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "160119": {
            "name": "南方中证500ETF联接A",
            "amount": 1000,
            "price": "1.6331",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "012348": {
            "name": "天弘恒生科技指数(QDII)A",
            "amount": 1000,
            "price": "0.5881",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "000071": {
            "name": "华夏恒生ETF联接A",
            "amount": 1000,
            "price": "1.1167",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "001180": {
            "name": "广发医药卫生联接A",
            "amount": 1000,
            "price": "0.9025",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "013395": {
            "name": "华夏新能源车龙头混合发起式A",
            "amount": 1000,
            "price": "0.8757",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "002656": {
            "name": "南方创业板ETF联接A",
            "amount": 1000,
            "price": "1.0849",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        },
        "000248": {
            "name": "汇添富中证主要消费ETF联接A",
            "amount": 1000,
            "price": "2.5260",
            "unitPrice": 0,
            "earnings": 0,
            "priceDate": "2023-07-24"
        }
    },
    "leek-fund.binance": [

        "BTC_USDT",
        "ETH_USDT",
        "EOS_USDT"
    ],
    "leek-fund.labelFormat": {
    
        "statusBarLabelFormat": "「${name}」${price}  ${icon}（${percent}）",
        "sidebarStockLabelFormat": "${icon|padRight|4}${percent|padRight|11}${price|padRight|15}「${name}」",
        "sidebarFundLabelFormat": "${icon|padRight|4}${percent|padRight}「${name}」${earnings} ${time}"
    },
}

**Comment by 54Ezreal** [comment]
+1

**Comment by MissDelia** [comment]
+1

**Comment by caokangx** [comment]
+1

**Comment by reclock** [comment]
一样的问题，咋解决的

**Comment by MouKim** [comment]
怎么解决 没法看收益了

**Comment by songshiquan** [comment]
使用旧版本也一样不行

**Comment by AndyCorssa** [comment]
2023年7月27日插件更新后依然无法显示关注基金内容

**Comment by akkentt** [comment]
前几天大部分平台都关闭了实时显示基金估值，导致插件差不到数据，已经没啥意义了  彻底废了

**Comment by lupingW** [comment]
+1

**Comment by albbandBlur** [comment]
> 前几天大部分平台都关闭了实时显示基金估值，导致插件抓不到数据，已经没啥意义了彻底废了

其实你看提交记录那边，其实已经有提交更换查询的接口并且修复下拉的问题，但是一直不合并至master并更新。不懂是为啥

**Comment by fanleung** [comment]
> > 前几天大部分平台都关闭了实时显示基金估值，导致插件抓不到数据，已经没啥意义了彻底废了
> 
> 其实你看提交记录那边，其实已经有提交更换查询的接口并且修复下拉的问题，但是一直不合并至master并更新。不懂是为啥

同问，以为会更新到master，等了几天了

**Comment by lupingW** [comment]
那年更新呀

**Comment by giscafer** [comment]
抱歉，这几天没看Github , same issue #391

**Comment by giscafer** [comment]
版本 v[3.4.2](https://github.com/LeekHub/leek-fund/commit/02f91eca6fe9e21ac9d1cdb12b47d08d67790604) 已解决
