### ISSUE TITLE
无法显示基金列表

### ISSUE THREAD

**Issue by bbtli** [LeekHub/leek-fund#391]
## Bug Report

![image](https://github.com/LeekHub/leek-fund/assets/45780445/1a6caf04-66be-4dde-984f-579651e25d04)
无法展现基金列表，重新安装插件后，删除分组重新添加问题依然存在

**Comment by WinwayJia** [comment]
同样的问题

**Comment by MrLeeGit** [comment]
同样的问题，起码要把ETF能看到的基金显示出来呀

**Comment by cqupeng** [comment]
同

**Comment by 894752114** [comment]
只能看 STOCK, FUND分组点不开
