### ISSUE TITLE
大佬可以加个自选收益吗?或者设置成本价

### ISSUE THREAD

**Issue by feng1026** [LeekHub/leek-fund#393]

**Comment by kermit2020** [comment]
股票很有必要啊,就是因为找不到股票收益,感觉作用小了很多.

**Comment by giscafer** [comment]
> 股票很有必要啊,就是因为找不到股票收益,感觉作用小了很多.

没必要是，大家都会去看APP，然后买卖可能频繁，如果账号不能登陆同步，基本很少人愿意手动频繁维护。另外，账号不好做成同步，涉及到安全性问题
