### ISSUE TITLE
请问有快捷键吗？左侧的入口我设置成影藏了。需要快捷键调用出来

### ISSUE THREAD

**Issue by lrf1027430** [LeekHub/leek-fund#397]

**Comment by giscafer** [comment]
目前是鼠标右键。之前开发插件是没有这种快捷键的。现在没有跟进了解

**Comment by lrf1027430** [comment]
![image](https://github.com/LeekHub/leek-fund/assets/16607727/48260eb6-837a-4f1f-aa39-9ac958a72119)
![image](https://github.com/LeekHub/leek-fund/assets/16607727/8bbfbedf-d1e9-4253-afb4-783180d6f0c6)
你好。邮件也找不到怎么调用显示出来。我之前影藏过左侧的入口

**Comment by giscafer** [comment]
<img width="383" alt="image" src="https://github.com/LeekHub/leek-fund/assets/8676711/eedce30f-1d11-432e-85a7-bb24644a00da">

右键是长这样的，侧栏边上空白处右键
