### ISSUE TITLE
底部状态栏收益计算不正确

### ISSUE THREAD

**Issue by MrMJY** [LeekHub/leek-fund#399]
## Bug Report

底部状态栏收益计算不正确

## Current Behavior?

![image](https://github.com/LeekHub/leek-fund/assets/49824922/ebf1a6e8-4522-4fd2-b316-d3c7a3ac01fd)

##  Your Environment [Optional]

版本: 1.82.2 (user setup)
提交: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
日期: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by VantStark** [comment]
查了一下，好像计算的时候只取了 leek-fund.funds 这个配置的第一组的第一只基金的收益
![eb7ef51732b15e10ed1abd8542bdaa35.png](https://img.xicc.cc:9013/images/2023/10/31/eb7ef51732b15e10ed1abd8542bdaa35.png)

**Comment by lupingW** [comment]
有解决方案吗

**Comment by cqupeng** [comment]
同有问题

**Comment by giscafer** [comment]
应该是之前的PR，分组功能改出的问题。有空再看。欢迎PR

**Comment by lupingW** [comment]
> 应该是之前的PR，分组功能改出的问题。有空再看。欢迎
xin ku jia ji yi xia

**Comment by lupingW** [comment]
催更 催更 太想要这个功能啦
