### ISSUE TITLE
股票详情打不开，看不到实时视图

### ISSUE THREAD

**Issue by hzequn** [LeekHub/leek-fund#402]
提示：加载 Web 视图时出错: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state
版本：3.4.3

**Comment by giscafer** [comment]
未能重现。

**Comment by giscafer** [comment]
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/bd7554aa-7d93-4f2e-a826-90c86180790d">
