### ISSUE TITLE
每次打开vscode右下角都提示<检查到 [韭菜盒子] 插件有新版本，是否立即升级？>

### ISSUE THREAD

**Issue by gdlk888** [LeekHub/leek-fund#403]
每次都是替<检查到 [韭菜盒子] 插件有新版本，是否立即升级？>,但是你点击去升级又啥都没反应

##  Your Environment [Optional]

windows下

**Comment by giscafer** [comment]
升级就没了吧？什么版本？

**Comment by gdlk888** [comment]
每次打开编辑器就是,

点击去升级又是

我的vscdoe是最新版的,已经很久之前就是这种情况了
没有地方升级,(





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicky ***@***.***&gt;; 
发送时间: 2023年11月3日(星期五) 下午5:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeekHub/leek-fund] 每次打开vscode右下角都提示<检查到 [韭菜盒子] 插件有新版本，是否立即升级？&gt; (Issue #403)





 
升级就没了吧？什么版本？
