### ISSUE TITLE
看不到基金！

### ISSUE THREAD

**Issue by chifenglovekele** [LeekHub/leek-fund#405]
**### 看不到基金模块了**
![微信截图_20231107100450](https://github.com/LeekHub/leek-fund/assets/25765625/6fbfefeb-1e59-4b4d-8395-f3f12ef64c8a)

**Comment by chifenglovekele** [comment]
使用的最新的v3.4.4，但是几个月前就看不到基金了！

**Comment by giscafer** [comment]
可能是你新增了某个基金数据引起了异常。建议进入设置，删除后边新增的基金code，或者全删了，用排除法找出哪个有问题。

**Comment by chifenglovekele** [comment]
还是不行哦，删完了，添加一个还是不行
![Uploading 微信截图_20231113203336.png…]()

**Comment by chifenglovekele** [comment]
还是不行哦，删完了，添加一个还是不行
![微信截图_20231113203336](https://github.com/LeekHub/leek-fund/assets/25765625/048e2359-67c7-4857-b38b-6704765b9212)

**Comment by giscafer** [comment]
Ctrl + Shift +P , 输入developer 找那个VSCode 的调试工具，然后刷新基金列表。看有啥错误

**Comment by chifenglovekele** [comment]
打开调试工具，一直报这个错误，一直报
![微信截图_20231114101916](https://github.com/LeekHub/leek-fund/assets/25765625/f34e587b-89e0-4cd9-94ee-6ad3ead29c57)

**Comment by chifenglovekele** [comment]
然后点击基金的刷新，没用报错，也没发送请求

**Comment by giscafer** [comment]
你不会是删完点击刷新吧，要有基金code才行

**Comment by chifenglovekele** [comment]
不是吖，你看测试这个分组里面，还有一个基金的！

**Comment by chifenglovekele** [comment]
不是吖，你看测试这个小组里面，还有一个基金的！

**Comment by chifenglovekele** [comment]
![微信截图_20231115152120](https://github.com/LeekHub/leek-fund/assets/25765625/0f4254d4-1e3a-43db-8698-b0c63ae92aeb)
感觉是雪球被内网屏蔽了

**Comment by giscafer** [comment]
很简单的排除法方式，你用自己手机热点试试行不行

**Comment by chifenglovekele** [comment]
确定是内网屏蔽了接口调用

**Comment by chifenglovekele** [comment]
但是为啥用翻墙软件，还是被屏蔽，奇怪

**Comment by giscafer** [comment]
不奇怪，用了它的网络就跳不出。
