### ISSUE TITLE
混合基金净值估算图停在2023-12-27

### ISSUE THREAD

**Issue by Jinxhao18** [LeekHub/leek-fund#414]
## Bug Report

混合基金净值估算图停在2023-12-27
## Current Behavior?

![image](https://github.com/LeekHub/leek-fund/assets/32037648/15bd4c35-c2ca-42c7-b1b2-b732b135d5cf)

## Expected Behavior?
正常更新

##  Your Environment [Optional]

macos 14.3  m1 mbp

**Comment by giscafer** [comment]
可能跌太多了，没脸更新了。

**Comment by giscafer** [comment]
政策规定不能展示净值了，支付宝等也是有些基金没有净值的。
