### ISSUE TITLE
状态栏显示的股票数目是否能调整

### ISSUE THREAD

**Issue by Tim0thy1** [LeekHub/leek-fund#415]
![image](https://github.com/LeekHub/leek-fund/assets/37064389/d74fdf9e-6f42-47b5-b97d-839f52b9b46b)

状态栏显示的股票数目固定在4个吗？是否能调多一点

**Comment by giscafer** [comment]
https://github.com/LeekHub/leek-fund/blob/1294588572da0b44ee90b24dcf53a9344db1ccd6/src/statusbar/statusBar.ts#L78C55-L78C79

支持配置，VSCode插件配置项搜：leek-fund.statusBarStock
