### ISSUE TITLE
股票每日收益显示错误

### ISSUE THREAD

**Issue by iaojnh** [LeekHub/leek-fund#417]
## Bug Report

![image](https://github.com/LeekHub/leek-fund/assets/38692278/6c387b39-1b21-4328-9443-f688f7f14181)
股票的每日收益被计算成了 当前价格-当日开盘价，应为 当前价格-昨日收盘价
![image](https://github.com/LeekHub/leek-fund/assets/38692278/45fc4e5e-70e9-4a82-a43c-14408ded287b)

**Comment by lmhtolin** [comment]
已经解决https://github.com/LeekHub/leek-fund/pull/420， @giscafer @iaojnh
