### ISSUE TITLE
statusBarStock  中的股票必须在 stocks 中设置了才会出现

### ISSUE THREAD

**Issue by xgdgsc** [LeekHub/leek-fund#418]
## Bug Report
statusBarStock  中的股票必须在 stocks 中设置了才会出现
 
## Current Behavior?
 statusBarStock  中的股票必须在 stocks 中设置了才会出现
 

## Expected Behavior?
只在 statusBarStock 中设置股票也能正常显示,

## Steps to reproduce [Optional]
statusBarStock  中加入
 sh000016
但不在 stocks  中加入, 则状态栏不显示此股票

##  Your Environment [Optional]
 Windows

**Comment by giscafer** [comment]
statusBar 的数据可能是 从 stocks 读取的，依赖关系
