### ISSUE TITLE
能否支持界面颜色修改？

### ISSUE THREAD

**Issue by MinardW** [LeekHub/leek-fund#419]
现在点开某只股票实时走势，**“分时“栏目的底色是亮黄色**，在VS Code的黑色主题中显得额外亮眼。

在韭菜中心的左下角，有个老板模式，可以让当前窗口变灰或者变暗，但在实时走势中无法使用。

因此，所以能否在个性定制中，加一个能自定义配置或者修改一些默认颜色比较亮的地方？

**Comment by giscafer** [comment]
这个不能单独控制，只能整体控制。因为走势是嵌入的页面
