### ISSUE TITLE
期望在大的分组下，支持更细致的分组功能

### ISSUE THREAD

**Issue by cMing1997** [LeekHub/leek-fund#424]
## Feature Request
1、自选的股票其实很多的时候 是很杂的，来源也会很广，比如 概念有 AI、传媒、汽车出行、也或者别人分享的，但是总共都在大的分组下进行散着排列的，查找的其实还是比较废事的
2、A股总是周期性的，这段时间涨这个概念，那段时间涨另外一个概念，所以期望有个分组之后，可以在某段时间内，可以方便的注意那一个概念内的自选股

**Comment by duoni2023** [comment]
fund的右边不是有个新增组功能吗

**Comment by cMing1997** [comment]
> fund的右边不是有个新增组功能吗

股票。不是基金，也就是  STOCK  并没有这个功能

**Comment by duoni2023** [comment]
> > fund的右边不是有个新增组功能吗
> 
> 股票。不是基金，也就是 STOCK 并没有这个功能

那确实没有 不知道是否可以改配置文件进行修改 估计得慢慢等

**Comment by giscafer** [comment]
有置顶功能了。A股什么垃圾概念都有，一会低空飞行，一会kimi概念，没啥用。

需要重点关注就置顶就好了
