### ISSUE TITLE
期货怎么添加啊, 怎么都找不到

### ISSUE THREAD

**Issue by 18814373105** [LeekHub/leek-fund#426]
只想知道在哪操作添加, 搜索不到

**Comment by giscafer** [comment]
![image](https://github.com/LeekHub/leek-fund/assets/8676711/86379657-1f42-4f56-bbb9-1ae684f94ba8)

**Comment by 18814373105** [comment]
感谢大佬回答, 可是搜不到我想要看的期货品种,  如: 螺纹, 豆粕 之类的

**Comment by 18814373105** [comment]
![image](https://github.com/LeekHub/leek-fund/assets/164473424/0d36c42a-4b46-4ed8-83d7-7847bff1ca72)

**Comment by Tim0thy1** [comment]
@giscafer 大神，HK的怎么添加啊，点了加号也不行。 如果手动的话，这个股票代码是怎么写？

**Comment by giscafer** [comment]
@Tim0thy1 这不直接搜可以吗？
![image](https://github.com/LeekHub/leek-fund/assets/8676711/3a904646-6210-465e-bd9b-3e704dbef3af)
