### ISSUE TITLE
功能建议：能否增加股票热榜功能

### ISSUE THREAD

**Issue by SolitaryGarrison** [LeekHub/leek-fund#429]
## 作者是否考虑增加查看同花顺、雪球等股票热榜

1.希望可以在韭菜盒子上查看同花顺，雪球东财等软件的股票热榜
![20240401-103518](https://github.com/LeekHub/leek-fund/assets/130976919/5964574f-496f-43a9-88cf-e918cf50b222)

**Comment by giscafer** [comment]
韭菜中心有。
