### ISSUE TITLE
运行五六分钟后会卡住不更新界面

### ISSUE THREAD

**Issue by jgs555** [LeekHub/leek-fund#440]
V3.7.1版本或者前一个版本都试过了，5月13号开始，打开vscode后，运行大约5分钟后，所有数据面板会卡住不更新，但是点到扩展管理后，底部的当日盈利情况就会更新，切到其它标签就不会更新了。A Stock里一直卡着不动，退出vscode再进后也是会在五六分钟后卡住。重新卸载安装后还是不行。

**Comment by jgs555** [comment]
![image](https://github.com/LeekHub/leek-fund/assets/20762144/d0095f07-ee1f-40e4-a11a-b418f1116ae1)
未见控制台报错。

**Comment by jgs555** [comment]
![image](https://github.com/LeekHub/leek-fund/assets/20762144/08f6b946-c65b-406e-9cb3-eb429c83c8ca)
好像是接口不稳定引起的，上次的还没返回，下次就发起请求。加上这个好像可以，明天再看看。

**Comment by giscafer** [comment]
别开VPN，接口不支持外网访问

**Comment by jgs555** [comment]
> 别开VPN，接口不支持外网访问

未开vpn，之前正常使用了一两年。就这个星期开始出现异常，可能是公司网络问题。卡住后，切换到手机热点，过一会儿上面的滚动条就会刷刷刷的滚动几次后正常，应该是一个调用接口一直在调用没有关闭，后面的堵塞了吧。

**Comment by ALongLi** [comment]
我的也是，开了这个公司网络直接不行了,直接session爆了
![image](https://github.com/LeekHub/leek-fund/assets/20749911/7bbb2955-6fc7-4f8b-91a0-8187108563a1)

把这个插件关了，就行了

**Comment by giscafer** [comment]
> 我的也是，开了这个公司网络直接不行了,直接session爆了 ![image](https://private-user-images.githubusercontent.com/20749911/336709984-7bbb2955-6fc7-4f8b-91a0-8187108563a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODc2MTYsIm5iZiI6MTcxODM4NzMxNiwicGF0aCI6Ii8yMDc0OTkxMS8zMzY3MDk5ODQtN2JiYjI5NTUtNmZjNy00ZjhiLTkxYTAtODE4NzEwODU2M2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE3NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzQ2ZmJjODJlY2ZjYjVmYmE2YjgzYzQ3ZWI4ZTI2ZDUwMTY1YWMyNTg0NjQwZWQ2YTc0ODFlNDI1N2ZlNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yAloTZE-q5ikNS5KYEGOsA-e1MJKlYTOJSE-ewigDgc)
> 
> 把这个插件关了，就行了

#446 #447

**Comment by giscafer** [comment]
v3.9.2 版本已经修复卡顿问题
