### ISSUE TITLE
270023 这个基金添加进去看不到

### ISSUE THREAD

**Issue by xkhanhan** [LeekHub/leek-fund#442]
<img width="382" alt="image" src="https://github.com/LeekHub/leek-fund/assets/61129468/47f64ccc-d8a5-4ea8-b60f-81ac3e66da5c">

**Comment by giscafer** [comment]
因为270023接口没有拿到数据。https://fundgz.1234567.com.cn/js/270023.js?rt=1716627600183 

其他正常的拿得到：https://fundgz.1234567.com.cn/js/013478.js?rt=1716627600183

https://github.com/LeekHub/leek-fund/blob/fe566f241db39e13a3177ab72ce5e10afb737f08/src/explorer/fundService.ts#L177

**Comment by giscafer** [comment]
https://github.com/LeekHub/leek-fund/blob/fe566f241db39e13a3177ab72ce5e10afb737f08/src/explorer/fundService.ts#L177  @James-chok

**Comment by giscafer** [comment]
same as #435
