### ISSUE TITLE
个股K线图的背景颜色太亮眼

### ISSUE THREAD

**Issue by pengxingsong** [LeekHub/leek-fund#443]
## Feature Request
希望作者对这个颜色做暗化调整，或者换成一个更隐藏的颜色。这个颜色相对本软件的定位来说，过于鲜艳了。

![image](https://github.com/LeekHub/leek-fund/assets/10624015/b519452e-4362-45bd-bc33-b3c43a931fc7)

**Comment by giscafer** [comment]
这是嵌入的页面，改不了。都长期打开了，建议打开网页版
