### ISSUE TITLE
运行时状态 未捕获错误一直在循环  时间长了编辑器就卡死了

### ISSUE THREAD

**Issue by iarjian** [LeekHub/leek-fund#444]
## Bug Report
运行时状态 未捕获错误一直在循环  时间长了编辑器就卡死了
![image](https://github.com/LeekHub/leek-fund/assets/28347543/f30715de-18d1-4145-9d31-70e514246d65)

##  Your Environment [Optional]

![image](https://github.com/LeekHub/leek-fund/assets/28347543/0eff24f1-74e1-49b1-aec6-a9b491c17b0b)

**Comment by iarjian** [comment]
好像是 OUTPUT 的 Flash News的报错  开始会一直循环报错  关闭后没有报错了

**Comment by giscafer** [comment]
#446 #447
