### ISSUE TITLE
CPU占用很高

### ISSUE THREAD

**Issue by hzysoft** [LeekHub/leek-fund#446]
每次打开vscode， 因为韭菜盒子，CPU占用一直15%左右，禁用韭菜盒子插件之后，一切正常了。

**Comment by hzysoft** [comment]
找到原因了，开启了”快讯输出“导致的，关掉这个选项CPU就正常了。

**Comment by giscafer** [comment]
也许也需要关注一下优化空间。

**Comment by giscafer** [comment]
v3.9.2 已修复此问题
