### ISSUE TITLE
运行卡死 影响电脑的网络

### ISSUE THREAD

**Issue by MrLeeGit** [LeekHub/leek-fund#447]
苹果Mac mini机器 vscode中运行插件时，会导致电脑网络阻塞（浏览器和其它联网软件连网异常缓慢），该插件数据也无法加载完毕，我判断可能是频繁请求接口数据未返回结果导致的，新版本和安装之前的版本现在都会有这种问题，希望发版修复这个bug。

**Comment by giscafer** [comment]
需要更多信息。开启VSCode开发者界面看日志截图。Cmd+shift+p, 选择 Develper: Open Webview Developer Tool

**Comment by giscafer** [comment]
或者试试关闭快讯试试？，参考 #446

**Comment by Zhou-Bill** [comment]
我也有同样的问题，这个问题我看了很久才发现原来是该插件问题。。。

**Comment by MrLeeGit** [comment]
Cmd+shift+p, 选择 Develper: Open Webview Developer Tool方式不能调出vscode的调试模式，截图信息供参考，不知是否有帮助

![image](https://github.com/LeekHub/leek-fund/assets/29703674/6ac41c40-0197-49b7-94d8-a55f631cbe59)

**Comment by MrLeeGit** [comment]
韭菜盒子 ---> 设置icon --->  扩展设置 ---> 关闭开启快讯输出 
按照此步骤后网络卡顿问题得到解决

**Comment by Zhou-Bill** [comment]
<img width="590" alt="image" src="https://github.com/LeekHub/leek-fund/assets/13554001/88f034f5-4980-49e0-a6af-2170a0a5001c">

关闭快讯也不行

**Comment by giscafer** [comment]
> Cmd+shift+p, 选择 Develper: Open Webview Developer Tool方式不能调出vscode的调试模式，截图信息供参考，不知是否有帮助
> 
> ![image](https://private-user-images.githubusercontent.com/29703674/341288077-6ac41c40-0197-49b7-94d8-a55f631cbe59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzcwNTUsIm5iZiI6MTcxOTAzNjc1NSwicGF0aCI6Ii8yOTcwMzY3NC8zNDEyODgwNzctNmFjNDFjNDAtMDE5Ny00OWI3LTk0ZDgtYTU1ZjYzMWNiZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA2MTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YmM0YjQ4NDU5ZjdkZjc5ZGE3ZTZkZjc5ZWE2MjM5MDZkMDdmYWEyZGMyYjhkYWY2YzhiOGUwZTJkODczZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRMqrD5kMECy5jX__9Lq8nJJIc8nLa6w8W8ZHVRzQHg)

这个是网络不通。右下角有链接，你浏览器打开可能也不行的。

> 韭菜盒子 ---> 设置icon ---> 扩展设置 ---> 关闭开启快讯输出 按照此步骤后网络卡顿问题得到解决

这这里切换启用/关闭
![image](https://github.com/LeekHub/leek-fund/assets/8676711/c6069534-9a49-4cde-bbb9-3841d5b879b7)

**Comment by Zhou-Bill** [comment]
![image](https://github.com/LeekHub/leek-fund/assets/13554001/ff361509-ad1b-4fc1-a132-6b8fae87a11f)
这个好像调用太频繁了吧

**Comment by giscafer** [comment]
@Zhou-Bill 这个是轮询查股票的。正常展示status bar 和左侧栏是不会轮询了。还有闭市时间也不轮询
