### ISSUE TITLE
新增股票时搜索不到，使用代码和名称都是

### ISSUE THREAD

**Issue by renoyuan** [LeekHub/leek-fund#454]
##  Your Environment [Optional]

![Uploading image.png…]()

**Comment by wieniawski-lai** [comment]
同样不能添加新的股票
![图片](https://github.com/user-attachments/assets/76eb2e04-e921-4e9d-8147-d313964a858a)

**Comment by giscafer** [comment]
> 同样不能添加新的股票 ![图片](https://private-user-images.githubusercontent.com/70927596/365022742-76eb2e04-e921-4e9d-8147-d313964a858a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTcyNjgsIm5iZiI6MTcyNTY5Njk2OCwicGF0aCI6Ii83MDkyNzU5Ni8zNjUwMjI3NDItNzZlYjJlMDQtZTkyMS00ZTlkLTgxNDctZDMxMzk2NGE4NThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA4MTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmUwNjE5NWRiZWZkODA5M2MwNjc5ODEzODQ1ODM5MDJlNDQwYjZjZjgyMWIzZWUyOGU1NjUxMjEwYmQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxZp_AbP_UPyw2wF3-TkniW-ApDsy9W9b9-M6P8JPt8)

再试试看行不行

**Comment by wieniawski-lai** [comment]
> > 同样不能添加新的股票 ![图片](https://private-user-images.githubusercontent.com/70927596/365022742-76eb2e04-e921-4e9d-8147-d313964a858a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTcyNjgsIm5iZiI6MTcyNTY5Njk2OCwicGF0aCI6Ii83MDkyNzU5Ni8zNjUwMjI3NDItNzZlYjJlMDQtZTkyMS00ZTlkLTgxNDctZDMxMzk2NGE4NThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA4MTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmUwNjE5NWRiZWZkODA5M2MwNjc5ODEzODQ1ODM5MDJlNDQwYjZjZjgyMWIzZWUyOGU1NjUxMjEwYmQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxZp_AbP_UPyw2wF3-TkniW-ApDsy9W9b9-M6P8JPt8)
> 
> 再试试看行不行

昨天行了一下,今天又不行了.

**Comment by Freesword** [comment]
现在还不行那个

**Comment by Nightwish555** [comment]
之前才行了一下，突然又不行了
