### ISSUE TITLE
添加标的接口疑似出现问题

### ISSUE THREAD

**Issue by Ryogi-Shiki** [LeekHub/leek-fund#456]
## Bug Report

似乎出现了添加标的失败的bug
## Current Behavior?

现在添加观察的标的，右下角回提示添加成功，但是观察栏里不会添加上去

出现的报错：
fail: Stock error https://hq.sinajs.cn/list=sh000001,sh000300,sh000016,sh000688,usr_ixic,usr_dji,usr_inx,nf_IF0,nf_IH0,nf_IC0,nf_IM0,hf_OIL,nf_FG0,nf_SR0,nf_SA0,nf_C0,nf_AG0,nf_M0,nf_AU0,nf_RB0,nf_PX0,nf_Y0,nf_SC0,hf_RS,hf_FEF,nf_SR2409,nf_EB2412,hf_XAG,hf_AHD,nf_AL0,sh603986,nf_RU0
## Expected Behavior?

我搜索品种时能搜到，那么理论上也应该可以添加成功。

**Comment by giscafer** [comment]
VPN 得问题？新浪接口是对这个敏感的

**Comment by Ryogi-Shiki** [comment]
> VPN 得问题？新浪接口是对这个敏感的

已解决，我把vscode和插件干净德卸载了一遍后重装就可以了。
