### ISSUE TITLE
早上一更新就完犊子了 Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by jgh004** [LeekHub/leek-fund#459]
基金显示正常，股票数据都没了，包括分组也没有了。然后一直提示 Cannot read properties of null (reading 'length')。
vsc版本
版本: 1.92.2 (user setup)
提交: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
日期: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

上移，下移，置顶操作异常。显示 接口不支持该股票 。

**Comment by xlzuijia** [comment]
我也是重新设置了一下股票分组

**Comment by ityadong** [comment]
我也是，回退版本也不行，会报code.startsWith is not a function

**Comment by ajsonx** [comment]
更新完原有分组不见了，只剩一个分组了。并且删除股票有问题

**Comment by jgh004** [comment]
上移，下移，置顶操作异常。显示 接口不支持该股票 。

**Comment by iced-duck** [comment]
"leek-fund.stocks": [
        null,
        "sh516550",
        "sz002036",
        "sh000001",
        "usr_ixic",
        "usr_dji",
        "usr_inx",
        "sh513180",
        "sh562500",
        "sh515790",
        "sh588000",
        "sh512880",
        "sh512690",
        "sz159938",
        "sh512170",
        "sh511090"
    ],
    
编辑settings.json    把这个null去掉

**Comment by MtSatou** [comment]
> 我也是，回退版本也不行，会报code.startsWith is not a function

删除settings.json 里 leek-fund.stocks配置的数组
"leek-fund.stocks": [
    [
      "nf_IF0",
      "nf_IH0",
      "nf_IC0",
      "nf_IM0",
      // [],    <---
      // []     <---
    ]
  ]

**Comment by giscafer** [comment]
@gittig11 出来改bug了

**Comment by giscafer** [comment]
错误问题我修复了，但是别的功能不正常，还需要PR作者处理或者我有时间再处理。
