### ISSUE TITLE
Stock分组之后无法使用置顶等功能

### ISSUE THREAD

**Issue by giscafer** [LeekHub/leek-fund#460]
相关问题：https://github.com/LeekHub/leek-fund/issues/459 

相关pr: https://github.com/LeekHub/leek-fund/pull/458

- 添加股票
- 移除股票
- 排序
- 置顶
- 刷新股价
- 韭菜中心监听股价
- 状态栏设置股票
- ……

都建议测一遍。

**Comment by rcnicky** [comment]
#461

**Comment by gittig11** [comment]
修复PR：https://github.com/LeekHub/leek-fund/pull/463

**Comment by giscafer** [comment]
bug 太多了，分组功能回滚了 ，请安装版本`v3.11.0`
