### ISSUE TITLE
新版本报错

### ISSUE THREAD

**Issue by XyhBill** [LeekHub/leek-fund#461]
## Bug Report

删除任意股票 都提示
Stock Successfully delete.
删除期货不成功。请 [点击此处](https://github.com/LeekHub/leek-fund/issues/281) 查看期货相关问题
上面的issues并未提供处理办法
## Current Behavior?

无法删除 置顶 移动等操作

##  Your Environment [Optional]

win10 vscode1.9.2 插件版本3.10.2

**Comment by TreasureLX** [comment]
我也出现了同样的问题，我把上证指数指定，直接分组都没了

**Comment by giscafer** [comment]
[3.10.3](https://github.com/LeekHub/leek-fund/commit/0f12c8e9e7f365e015a91ee22c6431f1616b5982) 版本再试试

**Comment by giscafer** [comment]
bug 太多了，分组功能回滚了 ，请安装版本`v3.11.0`
