### ISSUE TITLE
希望VS的状态栏悬浮窗口上能有当天的趋势曲线

### ISSUE THREAD

**Issue by Andy365-365** [LeekHub/leek-fund#462]
## Feature Request
当鼠标放到状态栏的一个股票上时，在现有的悬浮窗口上能有当天的趋势曲线，这样就能直观的知道一天的走势，寻找时机，而不是费力的记着价位，或是利用别的软件查看趋势了。

**Comment by giscafer** [comment]
这个VSCode 目前的api能力不支持。
