### ISSUE TITLE
能否更新修复一下历史标的的分组？

### ISSUE THREAD

**Issue by shengminjie** [LeekHub/leek-fund#466]
之前添加的都自动按不同类型分组了的，上次更新bug以后，全部在一个分组里面了。
现在更新了，好像还是在一个分组里面，如果手动把他们全部重新归类太复杂了。
能否更新一下，一键或自动归类下……？谢谢

**Comment by giscafer** [comment]
bug 太多了，分组功能回滚了 ，请安装版本`v3.11.0`
