### ISSUE TITLE
所有股票都进入同一个分组，而且搜索添加股票搜不到

### ISSUE THREAD

**Issue by hunterlevesque** [LeekHub/leek-fund#467]
所有股票都进入同一个分组My Stocks，而且搜索添加股票搜不到。 
还有部分股票更新后直接丢失了。建议还是按照A和H分开

**Comment by robbiemie** [comment]
作者被抓了，软件不维护了

**Comment by flyfire-cn** [comment]
不是前几天才更新的版本吗？就是这个新更新的版本有问题啊 3.10开始就不正常了

**Comment by hunterlevesque** [comment]
> 作者被抓了，软件不维护了







> 作者被抓了，软件不维护了

。。。你可别造谣啊 哥们 有证据？？？

**Comment by giscafer** [comment]
bug 太多了，分组功能回滚了 ，请安装版本`v3.11.0`
