### ISSUE TITLE
一进入左侧韭菜盒子tab栏就报错code.startsWith is not a function

### ISSUE THREAD

**Issue by hanhango** [LeekHub/leek-fund#470]
大概从1周前开始，vscode一进入左侧韭菜盒子tab栏就报错code.startsWith is not a function，无法添加股票
<img width="553" alt="image" src="https://github.com/user-attachments/assets/a74212ba-efea-44b5-91af-553e444c611c">
期望大佬看看有没有解决方案，是不是需要重装vscode

**Comment by JiaoZiLang** [comment]
最新版本貌似在macbook 上不能用了

**Comment by JiaoZiLang** [comment]
![image](https://github.com/user-attachments/assets/4aeb0d09-953a-40a1-a43d-13243505cbd9)

**Comment by hanhango** [comment]
> 最新版本貌似在macbook 上不能用了

我也不清楚，我以为是我vscode出啥问题导致的😂

**Comment by giscafer** [comment]
我很烦。大家PR注意 自测呢，不然影响比较大。

看一下最新版` v3.11.5` 修复了没，我也只是盲改的。

**Comment by hanhango** [comment]
> 我很烦。大家PR注意 自测呢，不然影响比较大。
> 
> 看一下最新版` v3.11.5` 修复了没，我也只是盲改的。

大佬，报错消失了，但股票仍然无法搜索添加，不过已经添加过的可以正常刷新

**Comment by yuhaobin** [comment]
股票搜索依旧无法使用
环境信息如下：
平台：Windows10

韭菜盒子：v3.11.5

vscode:1.92.2

**Comment by WZXXSu** [comment]
股票无法搜索添加，基金功能正常
韭菜盒子：v3.11.5

**Comment by rootdan** [comment]
股票搜索无法使用
平台：Windows10
vscode：1.90.0
韭菜盒子：v3.11.5

**Comment by giscafer** [comment]
已知

**Comment by Skylerliutian** [comment]
还是会出现 code.startsWith is not a function 的 error
平台： mac os 13.2.1
vscode: 1.92.1
韭菜盒子：v3.11.5

**Comment by giscafer** [comment]
> 还是会出现 code.startsWith is not a function 的 error 平台： mac os 13.2.1 vscode: 1.92.1 韭菜盒子：v3.11.5

编辑json，stocks里去掉内层数组格式`[`

**Comment by Skylerliutian** [comment]
> > 还是会出现 code.startsWith is not a function 的 error 平台： mac os 13.2.1 vscode: 1.92.1 韭菜盒子：v3.11.5
> 
> 编辑json，stocks里去掉内层数组格式`[`

Solved, Thx

**Comment by hanhango** [comment]
> 再试试看行不行，周五接口确实不行

大佬，现在还是无法搜索添加股票呢

**Comment by lth0418** [comment]
> 再试试看行不行，周五接口确实不行

我还以为是我有问题。反复重启vscode。我现在mac还是不能搜索添加股票。另外之前有个版本我记得是可以添加分组之类的，怎么突然没了？

**Comment by giscafer** [comment]
> > 再试试看行不行，周五接口确实不行
> 
> 我还以为是我有问题。反复重启vscode。我现在mac还是不能搜索添加股票。另外之前有个版本我记得是可以添加分组之类的，怎么突然没了？

网友的PR造成这段时间bug太多，回退了代码。日后再自己实现出来吧。
