### ISSUE TITLE
港股接口报错

### ISSUE THREAD

**Issue by liuyuhang791034063** [LeekHub/leek-fund#474]
##  Your Environment [Optional]

<img width="448" alt="image" src="https://github.com/user-attachments/assets/580bb06b-d144-4904-bab7-b35cbed6d41c">

**Comment by Kcium** [comment]
+1

**Comment by YLJ77** [comment]
+1

**Comment by XyhBill** [comment]
+1
fail: HK Stock error https://stock.xueqiu.com/v5/stock/batch/quote.json?symbol=02331,00700,01810

**Comment by gogosee** [comment]
+1
fail: HK Stock error https://stock.xueqiu.com/v5/stock/batch/quote.json?symbol=
港股接口获取不到数据呢，是怎么回事呢

**Comment by ForrestSu** [comment]
+1

**Comment by giscafer** [comment]
`v3.12.0` #484
