### ISSUE TITLE
未捕获的错误，且大部分功能无法使用

### ISSUE THREAD

**Issue by LeeNNN** [LeekHub/leek-fund#477]
vscode版本为windows最新。插件版本为3.11.6   
从节前牛市开始插件就看不到数据了，一直提示该错误，重新安装无效
![image](https://github.com/user-attachments/assets/01884821-a9e2-46bf-82fd-59f1fbd5a9cd)

**Comment by 903352754** [comment]
+1 这样的情况感觉很久了
![image](https://github.com/user-attachments/assets/e9725ab0-a9f0-4e2c-a616-14a61d04eff1)

**Comment by LeeNNN** [comment]
![image](https://github.com/user-attachments/assets/fbb9fd9f-a3c9-4d7b-96a1-efd06cd4fc76)
暂时解决，把配置json中stocks内部的数组[ ]去掉就可以了

> +1 这样的情况感觉很久了 ![image](https://private-user-images.githubusercontent.com/78247179/374771702-e9725ab0-a9f0-4e2c-a616-14a61d04eff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTMzMjIsIm5iZiI6MTcyODQ1MzAyMiwicGF0aCI6Ii83ODI0NzE3OS8zNzQ3NzE3MDItZTk3MjVhYjAtYTlmMC00ZTJjLWE2MTYtMTRhNjFkMDRlZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA1NTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MTRhYmUxZmU4M2NkM2NmZWM2ZjNmYWJjMzMwOWQ4YzMzZmVkMTE1MTJiNzgyMDY3Y2JjNWJkMzkyNzI4YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nTqQGwcCYR-12Hz8NEyuGgK6KmcLo9Hqi4tTwup41g4)
