### ISSUE TITLE
左侧箭头显示种类的优化

### ISSUE THREAD

**Issue by adhehe** [LeekHub/leek-fund#495]
![image](https://github.com/user-attachments/assets/99e71f37-8ed1-4243-a928-9637946d481a)

建议分为三个等级，2%以下单箭头，2%-5%之间双箭头，5%以上三箭头，现在只有两种区分不了微涨还是大涨

**Comment by giscafer** [comment]
感觉没必要，三箭头会让界面紧凑间隔小了会影响美观

**Comment by adhehe** [comment]
那就换种说法：建议使用不同的图标以区分微涨、中涨、大涨
