### ISSUE TITLE
股票添加栏中搜索不到某一只股票。美股：NIO；中文名：蔚来汽车。

### ISSUE THREAD

**Issue by tyePhDCandy** [LeekHub/leek-fund#77]
## Current Behavior?
股票添加栏中搜索不到某一只股票。美股：NIO；中文名：蔚来汽车。

但是，通过在json设置中添加"usr_nio"，可以添加成功。

随后，点击左栏中的nio股票，右侧东方财富详情显示不出来，显示“undefined"。

附参考网址：
http://quote.eastmoney.com/us/NIO.html

**Comment by giscafer** [comment]
@tyePhDCandy 股票这里其实我不是很了解。

比如 

```

var stockEnity = {
    stockId: "NIO7",
    stockCode: "NIO",
    stockName: "蔚来",
    stockMarket: "7",
    gubaCode: "usNIO",
    MktNum: "106",
    UnifiedID:"106.NIO"
}
``` 

`MktNum` 表示 market number 

蔚来的 Market number 编码是 106， 别的美股大部分是 105 。

这个怎么区分需要告知一下。

**Comment by tyePhDCandy** [comment]
@giscafer 
我目前也不知道。我会试图去找一找，如有答案，会来评论。
